// @ts-nocheck: evidence fixture, bundled by build-render.mjs (the @f8-base-memo module is generated at build time)
// Fixture app for the F8 / S-03 rail evidence renders. NOT shipped (webpack entry of build-render.mjs only).
//
// REAL code: components/slide-thumbnail-strip.tsx, hooks/use-slide-rail-identity.ts (+ lib/slide-rail-identity.ts),
// hooks/use-stage-f-thumbnail-cache.ts (+ its structural-ack fence), and the viewer's `slideThumbnails` logic
// extracted verbatim from the BASE commit's presentation-viewer.tsx (generated by build-render.mjs).
// SUBSTITUTED: the viewer/iframe/Director are not mounted; their state is replayed by the small driver below,
// Layout's inventory GET is a window.fetch stub that serves the contract fixtures (no network), and the preview
// images are synthetic (intercepted by Playwright). The glue below mirrors the three viewer lines F8 added:
//   rows = railIdentityRows ?? slideThumbnails(base logic)      and      refresh() after the ack.
import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { SlideThumbnailStrip } from '@/components/slide-thumbnail-strip'
import { useSlideRailIdentity } from '@/hooks/use-slide-rail-identity'
import { useStageFThumbnailCache } from '@/hooks/use-stage-f-thumbnail-cache'
import { baseSlideThumbnails } from '@f8-base-memo'
import afterInsert from '@/scripts/fixtures/f8-slide-inventory/inventory-after-insert.json'
import afterReload from '@/scripts/fixtures/f8-slide-inventory/inventory-after-reload.json'

declare global { interface Window { __f8: any } }

const PID = 'f8-replay-on'
const OWNER = 'owner-a'
const SESSION = 'session-a'
const A = 'slide_8ea0a04600cf', B = 'slide_51f6389579d6', N = 'slide_06137799b27f', C = 'slide_d960ba5dbd63'
const clone = <T,>(v: T): T => JSON.parse(JSON.stringify(v))
const row = (id: string, index: number, source: any) => ({ ...clone(source.slides.find((s: any) => s.slide_id === id)), slide_index: index })
const inventoryOf = (order: string[], source: any) => ({ presentation_id: PID, slide_count: order.length, slides: order.map((id, i) => row(id, i, source)) })
// Server states: 0 built deck A,B,C; 1 after the middle insert (A,B,N,C); 2 after N is moved to the end (A,B,C,N); 3 after delete A + append
const SERVER: Record<number, any> = {
  0: inventoryOf([A, B, C], afterInsert),
  1: afterReload,
  2: inventoryOf([A, B, C, N], afterInsert),
}
// Director's structure for the built deck (Director ids are slide_00x, Layout's are slide_{hex}).
const STRUCTURE = { metadata: { main_title: 'Deck' }, slides: [
  { slide_id: 'slide_001', title: 'Opening: why now', slide_type: 'title_slide' },
  { slide_id: 'slide_002', title: 'Market size and growth', slide_type: 'content_slide' },
  { slide_id: 'slide_003', title: 'Wrap-up and next steps', slide_type: 'closing_slide' },
] }

const query = new URLSearchParams(window.location.search)
const control = window.__f8 = {
  stage: 0, absent: query.get('absent') === '1', mode: (query.get('mode') === 'before' ? 'before' : 'after') as 'before' | 'after',
  generation: 0, fetchCalls: 0,
  set: (_: any) => {}, // replaced by the app
}
// Layout inventory stub: the contract's GET, from the fixtures. `absent` = backend flag off (405, like uat today).
window.fetch = (async (input: any) => {
  const url = String(input)
  if (!/\/slides\/inventory$/.test(url)) return new Response('{}', { status: 404 })
  control.fetchCalls++
  if (control.absent) return new Response(JSON.stringify({ detail: 'Method Not Allowed' }), { status: 405 })
  return new Response(JSON.stringify(SERVER[control.stage]), { status: 200, headers: { 'Content-Type': 'application/json' } })
}) as typeof fetch

function App({ generation }: { generation: number }) {
  const [, force] = useState(0)
  useEffect(() => { control.set = () => force(n => n + 1) }, [])
  const { stage, mode } = control
  // The viewer's state as the native Add / reorder acks leave it (presentation-viewer.tsx handleAddSlide).
  const [modified, setModified] = useState(false)
  const [framesSeeded, setFramesSeeded] = useState(false)
  const totalSlides = SERVER[stage].slide_count
  const cache = useStageFThumbnailCache({ enabled: true, ownerUserId: OWNER, sessionId: SESSION })
  const { thumbnailUrls, setReceivedThumbnailUrls, captureThumbnailMutation } = cache

  // slide_built frames: Stage F URLs by slide index, as the chat build delivers them (first mount of a fresh deck only).
  useEffect(() => {
    if (framesSeeded || control.generation > 0 || stage !== 0) return
    setFramesSeeded(true)
    setReceivedThumbnailUrls(PID, () => ({ [PID]: Object.fromEntries(SERVER[0].slides.map((s: any, i: number) => [i, s.thumbnail_url])) }))
  }, [framesSeeded, stage, setReceivedThumbnailUrls])

  // The structural ack (real fence): empties the presentation's index-keyed previews, as handleAddSlide does on ACK.
  useEffect(() => {
    (control as any).ack = () => {
      const owner = { presentationId: PID }
      const commit = captureThumbnailMutation(PID, owner)
      commit.fence(owner)               // viewer: commitThumbnailMutation.fence(expectedOwner) after the ack
      setModified(true)                 // viewer: commit(setSlidesModifiedByCrud, true)
      control.set()
    }
  }, [captureThumbnailMutation])

  const structureSlides = useMemo(() => !modified ? STRUCTURE.slides as unknown[] : null, [modified])
  const frames = useMemo(() => JSON.stringify(thumbnailUrls[PID] ?? {}), [thumbnailUrls])
  const { rows: identityRows, refresh } = useSlideRailIdentity({
    enabled: mode === 'after', presentationId: PID, ownerUserId: OWNER, structureSlides, refreshSignals: [totalSlides, frames],
  })
  useEffect(() => { (control as any).refresh = refresh }, [refresh])

  const today = useMemo(() => baseSlideThumbnails({
    railIdentityRows: null, slideStructure: STRUCTURE, totalSlides, slidesModifiedByCrud: modified,
    thumbnailUrlsBySlide: thumbnailUrls[PID] ?? {}, studioShell: true, presentationId: PID,
    studioCanonicalThumbnails: null, renderSlideMutationOwner: {},
    thumbnailNativeRevisionRef: { current: 0 }, thumbnailMetadataRef: { current: { revision: 0 } },
  }), [totalSlides, modified, thumbnailUrls])
  const slides = identityRows ?? today
  const current = Math.min(control.stage === 1 ? 3 : 1, slides.length)

  return (
    <div data-fixture-frame>
      <main className="canvas" aria-label="Canvas (fixture)">
        <div className="canvas-card">
          <strong>Canvas</strong>
          <span>Fixture: no slide is rendered here.</span>
          <span>Slide {current} of {totalSlides}</span>
        </div>
      </main>
      <aside className="rail" style={{ width: 168 }} data-studio-v4-thumbnails="true">
        <SlideThumbnailStrip
          slides={slides}
          currentSlide={current}
          onSlideClick={() => {}}
          orientation="vertical"
          totalSlides={totalSlides}
          keyBySlideId={identityRows !== null}
        />
      </aside>
    </div>
  )
}

function Root() {
  const [generation, setGeneration] = useState(0)
  useEffect(() => { (control as any).remount = () => { control.generation += 1; setGeneration(g => g + 1) } }, [])
  return <App key={generation} generation={generation} />
}
createRoot(document.getElementById('root')!).render(<Root />)
