import { Integration } from '@/types/integration';

export const integrations: Integration[] = [
  // Export Formats
  {
    id: 'powerpoint',
    name: 'PowerPoint',
    description: 'Export your presentations to Microsoft PowerPoint (.pptx) format with full formatting preservation.',
    category: 'export',
    status: 'available',
    logo: '/integrations/powerpoint.svg',
    features: [
      'Full slide export',
      'Formatting preservation',
      'Speaker notes included',
      'Animation support',
    ],
    setupDifficulty: 'easy',
    popular: true,
  },
  {
    id: 'pdf',
    name: 'PDF Export',
    description: 'Export to PDF with options for standard quality, high-resolution, or print-ready formats.',
    category: 'export',
    status: 'available',
    logo: '/integrations/pdf.svg',
    features: [
      'Standard quality',
      'High-resolution',
      'Print-ready format',
      'Embedded fonts',
    ],
    setupDifficulty: 'easy',
    popular: true,
  },
  {
    id: 'google-slides',
    name: 'Google Slides',
    description: 'Export directly to Google Slides or import from Google Drive. Seamless integration with Google Workspace.',
    category: 'export',
    status: 'available',
    logo: '/integrations/google-slides.svg',
    features: [
      'Direct export',
      'Import from Drive',
      'Real-time sync',
      'Collaborative editing',
    ],
    setupDifficulty: 'easy',
    popular: true,
  },
  {
    id: 'image-export',
    name: 'Image Export',
    description: 'Export individual slides as PNG or JPEG images in various resolutions.',
    category: 'export',
    status: 'available',
    logo: '/integrations/image.svg',
    features: [
      'PNG format',
      'JPEG format',
      'Multiple resolutions',
      'Batch export',
    ],
    setupDifficulty: 'easy',
  },
  {
    id: 'web-export',
    name: 'Web Presentation',
    description: 'Generate a shareable web link for your presentation with interactive navigation.',
    category: 'export',
    status: 'available',
    logo: '/integrations/web.svg',
    features: [
      'Shareable link',
      'Interactive navigation',
      'Mobile-friendly',
      'Analytics tracking',
    ],
    setupDifficulty: 'easy',
  },

  // Storage & Cloud
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Save and sync your presentations with Google Drive. Access from anywhere, collaborate with your team.',
    category: 'storage',
    status: 'coming-soon',
    logo: '/integrations/google-drive.svg',
    features: [
      'Auto-save to Drive',
      'Folder organization',
      'Team sharing',
      'Version history',
    ],
    setupDifficulty: 'easy',
    popular: true,
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Automatically save presentations to Dropbox and sync across all your devices.',
    category: 'storage',
    status: 'coming-soon',
    logo: '/integrations/dropbox.svg',
    features: [
      'Auto-sync',
      'File recovery',
      'Team folders',
      'Smart sync',
    ],
    setupDifficulty: 'easy',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    description: 'Integrate with Microsoft OneDrive for seamless storage and collaboration.',
    category: 'storage',
    status: 'coming-soon',
    logo: '/integrations/onedrive.svg',
    features: [
      'Cloud storage',
      'Office integration',
      'Team collaboration',
      'Auto-backup',
    ],
    setupDifficulty: 'easy',
  },

  // Communication
  {
    id: 'slack',
    name: 'Slack',
    description: 'Share presentations directly in Slack channels and receive notifications about team activity.',
    category: 'communication',
    status: 'coming-soon',
    logo: '/integrations/slack.svg',
    features: [
      'Share to channels',
      'Activity notifications',
      'Preview in Slack',
      'Collaboration alerts',
    ],
    setupDifficulty: 'moderate',
    popular: true,
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'Present and share directly within Microsoft Teams meetings and channels.',
    category: 'communication',
    status: 'coming-soon',
    logo: '/integrations/teams.svg',
    features: [
      'Share in meetings',
      'Channel integration',
      'Live presenting',
      'Team collaboration',
    ],
    setupDifficulty: 'moderate',
  },
  {
    id: 'email',
    name: 'Email Integration',
    description: 'Send presentations directly via email with customizable messages and tracking.',
    category: 'communication',
    status: 'coming-soon',
    logo: '/integrations/email.svg',
    features: [
      'Direct email sending',
      'Custom messages',
      'Open tracking',
      'Scheduled sending',
    ],
    setupDifficulty: 'easy',
  },

  // Content Sources
  {
    id: 'unsplash',
    name: 'Unsplash',
    description: 'Access millions of high-quality, royalty-free images directly from Unsplash.',
    category: 'content',
    status: 'coming-soon',
    logo: '/integrations/unsplash.svg',
    features: [
      'Millions of images',
      'Royalty-free',
      'High-resolution',
      'Direct insertion',
    ],
    setupDifficulty: 'easy',
    popular: true,
  },
  {
    id: 'pexels',
    name: 'Pexels',
    description: 'Browse and insert free stock photos and videos from Pexels.',
    category: 'content',
    status: 'coming-soon',
    logo: '/integrations/pexels.svg',
    features: [
      'Photos and videos',
      'Free to use',
      'Curated collections',
      'One-click insert',
    ],
    setupDifficulty: 'easy',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Embed YouTube videos directly into your presentations for engaging content.',
    category: 'content',
    status: 'coming-soon',
    logo: '/integrations/youtube.svg',
    features: [
      'Video embedding',
      'Custom start times',
      'Auto-play options',
      'Thumbnail preview',
    ],
    setupDifficulty: 'easy',
  },
  {
    id: 'giphy',
    name: 'Giphy',
    description: 'Add animated GIFs from Giphy to make your presentations more dynamic and engaging.',
    category: 'content',
    status: 'coming-soon',
    logo: '/integrations/giphy.svg',
    features: [
      'GIF library',
      'Search by keyword',
      'Trending GIFs',
      'Direct insertion',
    ],
    setupDifficulty: 'easy',
  },

  // Productivity
  {
    id: 'notion',
    name: 'Notion',
    description: 'Embed presentations in Notion pages and sync content between both platforms.',
    category: 'productivity',
    status: 'coming-soon',
    logo: '/integrations/notion.svg',
    features: [
      'Embed in pages',
      'Content sync',
      'Bi-directional updates',
      'Database integration',
    ],
    setupDifficulty: 'moderate',
    popular: true,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Automate workflows with 5000+ apps using Zapier. Trigger actions when presentations are created or updated.',
    category: 'productivity',
    status: 'coming-soon',
    logo: '/integrations/zapier.svg',
    features: [
      '5000+ app connections',
      'Workflow automation',
      'Custom triggers',
      'Multi-step zaps',
    ],
    setupDifficulty: 'advanced',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Connect presentation data with Airtable databases for advanced organization and tracking.',
    category: 'productivity',
    status: 'coming-soon',
    logo: '/integrations/airtable.svg',
    features: [
      'Database sync',
      'Content management',
      'Team collaboration',
      'Custom views',
    ],
    setupDifficulty: 'moderate',
  },
];

export const integrationCategories = [
  { value: 'export', label: 'Export Formats', count: integrations.filter(i => i.category === 'export').length },
  { value: 'storage', label: 'Storage & Cloud', count: integrations.filter(i => i.category === 'storage').length },
  { value: 'communication', label: 'Communication', count: integrations.filter(i => i.category === 'communication').length },
  { value: 'content', label: 'Content Sources', count: integrations.filter(i => i.category === 'content').length },
  { value: 'productivity', label: 'Productivity', count: integrations.filter(i => i.category === 'productivity').length },
];
