import type { Metadata } from "next"
import { Footer, Header } from "@/components/layout"
import { Hero } from "@/components/marketing/HomepageV2"

export const metadata: Metadata = {
  title: "Deckster — AI agents that build slides while you watch",
  description:
    "Nine element types, 18 chart variants, 34 diagram patterns, 14 infographic templates — all generated by four collaborating AI agents from a single prompt. PowerPoint and PDF export included.",
  alternates: { canonical: "/" },
  openGraph: {
    title: "Deckster — AI agents that build slides while you watch",
    description:
      "Nine element types, 18 charts, 34 diagrams, 14 infographics — generated by four collaborating AI agents from one prompt. PPTX & PDF export.",
    url: "https://deckster.xyz",
    siteName: "Deckster",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Deckster — AI agents that build slides while you watch",
    description:
      "9 element types, 18 charts, 34 diagrams, 14 infographics — from a single prompt. Watch four AI agents collaborate.",
    creator: "@deckster",
  },
}

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col bg-background font-sans selection:bg-primary/20">
      <Header />
      <main>
        <Hero />
        {/* Phase 2+: <BuilderDemo />, <ElementGallery />, <AgentChoreography />,
            <LivingCanvas />, <SocialProof />, <PricingV2 />, <FinalCTA /> */}
      </main>
      <Footer />
    </div>
  )
}
