import { AGENT_TEAM, type AgentId } from "@/lib/marketing/homepage-v2-content"

/**
 * Copy for marketing v3 (pass 2). Every claim here must be true today or carry a status pill.
 * Proposal and evidence: workspace marketing-v3/plan/PASS2_PROPOSAL.html and plan/audit/cap/*.md.
 */
const agentColor = (id: AgentId) => AGENT_TEAM.find((agent) => agent.id === id)!.color

/** Public status words (decision D-2). "live" means a paying customer can use it in production. */
export const V3_STATUS_WORDS = {
  live: "Live",
  beta: "Beta",
  build: "In build",
  planned: "Planned",
} as const

export type V3Status = keyof typeof V3_STATUS_WORDS

/** One place to change a feature's public status when it ships. */
export const V3_FEATURES = {
  publish: "live",
  approvals: "live",
  questions: "beta",
  narration: "beta",
  meetings: "planned",
  buildControl: "beta",
  slidePanel: "beta",
  templates: "beta",
  templateNewTopic: "build",
  templatePdf: "planned",
  sources: "live",
  themes: "live",
  themeSwitch: "planned",
  knowledgeGraph: "beta",
  teamSharing: "planned",
} as const satisfies Record<string, V3Status>

export type V3Feature = keyof typeof V3_FEATURES

export const V3_CONTENT = {
  metadata: {
    title: "Deckster — Your knowledge. Your decks. Your voice.",
    description:
      "Deckster plans your deck with you, waits for your yes, then builds every slide in your theme with sources on the charts. Edit any slide or chart yourself. In early access.",
  },
  nav: [
    { label: "Build", href: "/#zoom" },
    { label: "Bring", href: "/bring" },
    { label: "Present", href: "/present" },
    { label: "Experts", href: "/experts" },
    { label: "Pricing", href: "/pricing" },
  ],
  menuExtra: [
    { label: "Learn", href: "/learn" },
    { label: "About", href: "/about" },
  ],
  header: {
    home: "Deckster home",
    wordmark: "deckster",
    signIn: "Sign in",
    build: "Request access",
    open: "Open Deckster",
    menu: "Open menu",
    close: "Close menu",
  },
  footer: {
    copyright: "© 2026 deckster · Your knowledge. Your decks. Your voice.",
    links: [
      { label: "Bring", href: "/bring" },
      { label: "Present", href: "/present" },
      { label: "Experts", href: "/experts" },
      { label: "Pricing", href: "/pricing" },
      { label: "Learn", href: "/learn" },
      { label: "About", href: "/about" },
      { label: "Help", href: "/help" },
      { label: "Privacy", href: "/legal/privacy" },
      { label: "Terms", href: "/legal/terms" },
    ],
  },
  start: {
    label: "Start",
    eyebrow: "AI presentation studio · early access",
    title: ["Your knowledge.", "Your decks.", "Your voice."],
    lede:
      "Brief the Director and attach your documents. It proposes a plan, waits for your yes, then builds every slide in your theme — with sources on the charts.",
    build: "Request early access",
    see: "See how it builds",
    codeLead: "Have an access code? ",
    codeLink: "Sign in with Google",
    codeTail: " and start today.",
    facts: [
      "Plan approval before any slide is built",
      "Chart sources shown",
      "Edit any slide yourself",
      "PowerPoint & PDF, no watermark",
    ],
    cursor: "you",
    request: "make this chart a waterfall",
    agent: "Refine element · ",
    agentBold: "waterfall",
    agentSource: " · data, labels and source kept",
    cue: "See how it builds",
  },
  zoom: {
    label: "Precision",
    eyebrow: "Precision",
    title: "Control it at every altitude.",
    altitudes: ["Deck", "Slide", "Element"],
    foot: "Scroll to zoom in · deck → slide → element",
    tiles: [
      { slide: 1, tag: "01 · Title", title: "A new operating model moves" },
      { slide: 2, tag: "02 · How it works", title: "Driving Business Agility through a Five-Step Model" },
      { slide: 3, tag: "03", title: "Managing the Ownership Chain for Product Changes" },
      { slide: 4, tag: "04 · Analysis", title: "Strengthening the Six Capabilities of Modern Delivery" },
      { slide: 6, tag: "06", title: "Optimizing Decision Forums and Governance Cadence" },
      { slide: 7, tag: "07", title: "Teams Climb Five Levels of Delivery Maturity" },
      { slide: 8, tag: "08", title: "Where each decision should live" },
      { slide: 9, tag: "16 · Closing", title: "Next Wave Lowers Later Costs" },
    ],
    exchanges: [
      {
        altitude: "deck",
        who: "You → Director",
        request: "“Build a 16-slide operating-model review from my Q3 board pack.”",
        response:
          "Director · here's the plan: 3 sections, 16 slides, research on your uploads first. Does this structure work for you?",
        action: "Yes, let's build it!",
        secondary: "I'd like to make changes",
        secondaryHref: "/experts#loop",
      },
      {
        altitude: "slide",
        who: "You → Slide panel",
        feature: "slidePanel",
        request: "“Add a slide after 4 that compares decision latency by team.”",
        response:
          "Slide panel · composed in the deck's theme from your board pack and inserted after slide 4. The slides around it were read for context.",
        action: "Keep it",
        secondary: "Edit on the canvas",
        secondaryHref: "/learn",
      },
      {
        altitude: "element",
        who: "You → Refine element",
        request: "“Make this chart a waterfall.”",
        response: "Recreated as a waterfall · data, labels and source kept: Q3 board pack, slide 7.",
        tryLabel: "Try it",
      },
    ],
    modes: [
      { id: "bars", label: "Bars" },
      { id: "waterfall", label: "Waterfall" },
      { id: "line", label: "Line" },
      { id: "table", label: "Table" },
    ],
    slide: {
      eyebrow: "ANALYSIS",
      title: "Decision latency by ",
      titleAccent: "team",
      elements: {
        title: "Title",
        metrics: "Metrics ×3",
        chart: "Chart",
        text: "Text ×2",
        takeaway: "Takeaway",
      },
      metrics: [
        { value: "11 days", label: "Median decision" },
        { value: "48 h", label: "Target rule" },
        { value: "−23%", label: "Throughput gap" },
      ],
      chartTitle: "Days from request to decision, by team",
      waterfallTitle: "Where the 11 days go",
      chartSub: "Q3 · six delivery teams · your board pack",
      tableHead: ["Team", "Days"],
      bars: [
        { height: 70, base: 0, waterfallHeight: 36.4, value: "14", waterfallValue: "+4.0", label: "Platform", waterfallLabel: "Approval wait" },
        { height: 55, base: 36.4, waterfallHeight: 27.3, value: "11", waterfallValue: "+3.0", label: "Payments", waterfallLabel: "Handoffs" },
        { height: 85, base: 63.7, waterfallHeight: 18.2, value: "17", waterfallValue: "+2.0", label: "Risk", waterfallLabel: "Rework" },
        { height: 45, base: 81.9, waterfallHeight: 13.6, value: "9", waterfallValue: "+1.5", label: "Data", waterfallLabel: "Unsequenced starts" },
        { height: 40, base: 95.5, waterfallHeight: 4.5, value: "8", waterfallValue: "+0.5", label: "Mobile", waterfallLabel: "Other" },
        { height: 60, base: 0, waterfallHeight: 100, value: "12", waterfallValue: "11.0", label: "Ops", waterfallLabel: "Total" },
      ],
      sourceLabel: "SOURCE",
      source: "Q3 board pack · slide 7",
      sides: [
        {
          title: "What we saw",
          body: "Approvals wait a median of four days at domain level. Six in ten stalls were waiting on a decision already taken elsewhere.",
        },
        {
          title: "What to do",
          body: "Move decision rights to the lowest safe level. Anything stuck longer than 48 hours escalates one rung — automatically.",
        },
      ],
      takeaway: "Decision latency — not capacity — is the binding constraint on delivery.",
      foot: "Fixing delivery without adding headcount",
      number: "5 / 16",
    },
  },
  bring: {
    label: "Bring",
    eyebrow: "Bring what you have",
    title: "Start from what you already have.",
    lede: "Your documents, spreadsheets and brand colours go into the deck from the first brief. Past PowerPoints can become reusable templates — that part is in beta.",
    inputs: [
      { kind: "PPTX", name: "Q3 board pack.pptx", detail: "16 slides · presented in June" },
      { kind: "XLSX", name: "Throughput by team.xlsx", detail: "6 sheets · the numbers behind the charts" },
      { kind: "HEX", name: "Brand colour #16203A", detail: "navy, with a gold accent" },
    ],
    template: { title: "Template · Board pack", detail: "reuse it as it was, or with a new topic", alt: "Slide 11 of the showcase deck: Strengthening the Six Capabilities of Modern Delivery", feature: "templates", note: ".pptx" },
    knowledgeAsset: { title: "Sources · your files", detail: "charts and figures say where their numbers came from", feature: "sources" },
    themeAsset: { title: "Theme · navy & gold", detail: "preset or brand colour, set before the build", feature: "themes" },
    notes: [
      { title: "Decks become templates", feature: "templates", body: "Add a PowerPoint to your template library. Reuse it as it was, or ask for a new topic in the same layout — new-topic reuse is still being tuned." },
      { title: "Documents become sources", feature: "sources", body: "PDFs, Word files and spreadsheets are read for facts and figures. Charts built from them say where their numbers came from." },
      { title: "Brands become themes", feature: "themes", body: "Start from a preset or your brand colour and save it as your standard. Switching a finished deck to a new theme is planned." },
    ],
  },
  knowledge: {
    label: "Knowledge",
    eyebrow: "Knowledge graph",
    feature: "knowledgeGraph",
    title: "Every deck you make can teach the next one.",
    lede: "Switch it on, and the research and documents behind each deck join a graph that is yours. Later decks on related topics draw on it, and say so.",
    legend: { research: "from research", documents: "from your documents" },
    stats: { decks: "decks", facts: "facts", sources: "sources" },
    citation: {
      web: { label: "From the web", value: "Median approval latency in mid-size banks: 6.2 days", source: "Estimated · industry survey, 2025" },
      graph: { label: "Your knowledge", value: "Median approval latency at Northbank: 11 days", sourceLead: "Source: ", sourceStrong: "Q3 board pack, slide 7" },
    },
    checks: ["On or off per deck", "Browse it on your Knowledge page", "Delete it any time", "Never shown to your audience"],
  },
  experts: {
    label: "Experts",
    eyebrow: "Human in the loop",
    title: "You direct. Specialists build.",
    lede: "The Director plans the deck and hands the work to specialists for research, writing, charts and design. You approve the plan, watch the build, and edit any slide yourself.",
    you: { name: "you", role: "executive producer · the human in the loop" },
    director: { name: "Director", role: "· plans the deck, picks the specialist for each step — reports to you" },
    agents: [
      { id: "researcher", name: "Researcher", role: "your files and the web", color: agentColor("researcher") },
      { id: "content_generator", name: "Content", role: "headlines, body, notes", color: agentColor("content_generator") },
      { id: "visualizer", name: "Visualizer", role: "charts, diagrams, infographics", color: agentColor("visualizer") },
      { id: "theme_builder", name: "Theme Builder", role: "palette and type", color: agentColor("theme_builder") },
      { id: "slide_composer", name: "Slide Composer", role: "one slide into any deck", color: agentColor("slide_composer") },
      { id: "element_generator", name: "Element Generator", role: "one element at a time", color: agentColor("element_generator") },
    ],
    gates: [
      { number: "1", name: "Plan", action: "→ your yes" },
      { number: "2", name: "Outline", action: "→ your yes" },
      { number: "3", name: "Any slide", action: "→ your edit" },
    ],
    loop: {
      bar: "Build progress · slide 5 of 16",
      feature: "buildControl",
      pause: "Pause",
      resume: "Resume",
      stop: "Stop",
      pausedLine: "Paused — finishing what's in flight…",
      resumeLine: "Resuming your build…",
      stoppedLine: "Stopped — your progress is saved",
      note: "Finished slides stay. ",
      noteStrong: "Edit any of them on the canvas.",
      prefill: 5,
      script: [
        "Plan approved by you · 3 sections, 16 slides",
        "Outline ready — shaping your slides…",
        "Researching each slide in detail…",
        "Writing slide 4 of 16 — Six capabilities",
        "Writing slide 5 of 16 — Decision latency by team",
        "Running quality checks…",
        "Writing slide 6 of 16 — Where the 11 days go",
        "Evidence ready · slide 7",
        "Writing slide 7 of 16 — Decision forums",
        "Running quality checks…",
      ],
    },
  },
  themes: {
    label: "Themes",
    eyebrow: "Themes",
    title: "Set the look before it builds.",
    lede: "Pick a preset, start from your brand colour, or reuse the theme you saved as your standard. Titles, charts and diagrams are all built in it.",
    variants: [
      {
        id: "dark", name: "Dark", note: "same title, a different look",
        swatches: ["#0f2027", "#1e6f79", "#d3eef2"],
        images: ["theme-hero-dark-slide-01.jpg", "theme-hero-dark-slide-02.jpg"],
      },
      {
        id: "vibrant", name: "Vibrant", note: "warm metallics on ink",
        swatches: ["#2a2158", "#b58c4a", "#e9d8ff"],
        images: ["theme-hero-vibrant-slide-01.jpg", "theme-hero-vibrant-slide-02.jpg"],
      },
      {
        id: "abstract", name: "Abstract", note: "painterly title slides",
        swatches: ["#5f7f8a", "#c9a227", "#8b2252"],
        images: ["theme-abstract-slide-01.jpg", "theme-abstract-slide-02.jpg"],
      },
      {
        id: "industrial", name: "Industrial", note: "steel and signal orange",
        swatches: ["#1b1b1b", "#6b7280", "#f59e0b"],
        images: ["theme-industrial-slide-01.jpg", "theme-industrial-slide-02.jpg"],
      },
    ],
    panel: {
      title: "In the theme panel",
      items: [
        { text: "Presets", feature: "themes" },
        { text: "Your brand colour", feature: "themes" },
        { text: "A saved standard theme", feature: "themes" },
        { text: "Switch a finished deck to a new theme", feature: "themeSwitch" },
      ],
    },
  },
  present: {
    label: "Present",
    eyebrow: "Present",
    title: "Publish it. Then let it take questions.",
    lede: "One button gives your deck a link, with a passcode and the downloads you allow. In beta, viewers can ask it questions and it answers from your slides and documents. Narration and live meetings come next.",
    player: {
      urlPrefix: "deckster.xyz/p/", urlSlug: "k3Tq9xV2aB", access: "● passcode · 128 views",
      caption: "Slide 4 of 16", time: "narrated · 12 min", voice: "Narration · beta",
    },
    qa: {
      feature: "questions", title: "Questions", input: "Ask about this deck…",
      sequence: [
        { who: "viewer", kicker: "Viewer", text: "How does the 48-hour rule handle vendor calls?" },
        { who: "deck", kicker: "Answer", text: "Up to £250k they sit with domain leadership; anything larger escalates after 48 hours.", source: "From slide 6" },
        { who: "viewer", kicker: "Viewer", text: "What did the Q3 survey cost to run?" },
        { who: "deck", kicker: "Answer", text: "That isn't in this deck. I've passed it to the presenter.", source: "Sent to the owner's inbox" },
      ],
    },
    ladder: [
      { feature: "publish", text: "Publish · link or passcode, PDF and PowerPoint downloads you allow, view count, one-click republish" },
      { feature: "questions", text: "Questions · answers from your slides and documents; the rest goes to your inbox" },
      { feature: "narration", text: "Narration · a script per slide, read in one of nine stock voices, fitted to your time" },
      { feature: "meetings", text: "Live meetings · the deck joins Zoom, Meet or Teams" },
    ],
  },
  gallery: {
    label: "Gallery",
    eyebrow: "What they build",
    title: "Every shape your idea fits into.",
    lede: "Charts, diagrams, infographics and tables, in the deck's theme. Refine any one of them later without touching the rest of the slide.",
    counts: [
      { value: "9", label: "element types" },
      { value: "14", label: "chart types" },
      { value: "8", label: "diagram types" },
      { value: "Any", label: "infographic you describe" },
    ],
    wall: [
      { slot: 2, title: "Five-step model", shape: "chevrons" },
      { slot: 4, title: "Six capabilities", shape: "honeycomb" },
      { slot: 6, title: "Decision forums", shape: "pyramid" },
      { slot: 7, title: "Delivery maturity", shape: "staircase" },
      { slot: 8, title: "Where decisions live", shape: "2×2 matrix" },
      { slot: 10, title: "Four pillars", shape: "cards" },
      { slot: 11, title: "Rollout", shape: "timeline" },
      { slot: 12, title: "Hiring", shape: "funnel" },
    ],
    caption: "All eight from one deck Deckster built: “A new operating model moves”.",
  },
  realDeck: {
    label: "Real deck",
    eyebrow: "See for yourself",
    title: "Open a deck Deckster built.",
    lede: "“A new operating model moves”: 16 slides, built in Deckster from one brief and published with one button. Page through it, check the sources on its charts, download the PowerPoint.",
    open: "Open the deck",
    /** Public deckster.xyz/p/… link of the byline-free showcase deck. Empty = the slide and buttons stay hidden. */
    url: "",
    mosaic: [1, 2, 4, 6, 7, 11, 12],
  },
  pricingHome: {
    label: "Pricing",
    eyebrow: "Pricing · early access",
    title: "Priced for how often you present.",
    lede: "Deckster is in early access: sign in with Google and enter your access code, or ask for one. Plans differ by how much you can build each month. Top-ups never expire.",
    tiers: [
      { id: "starter", name: "Starter", price: "$20", suffix: "/ month", blurb: "For a deck every week or two.", features: ["The whole builder: research, your files, charts, diagrams, infographics", "PowerPoint & PDF export, no watermark", "Publish with a link or passcode", "$20 of building each month"], note: "Launch pricing · during early access, plans come with your access code.", cta: "Request access" },
      { id: "pro", name: "Pro", price: "$50", suffix: "/ month", blurb: "For people who present every week.", features: ["Everything in Starter, plus:", "$50 of building each month", "Room for research-heavy decks"], note: "Launch pricing · during early access, plans come with your access code.", cta: "Request access", tag: "Most popular" },
      { id: "max", name: "Max", price: "$100", suffix: "/ month", blurb: "For people who present as their core work.", features: ["Everything in Pro, plus:", "$100 of building each month", "Knowledge graph across your decks"], betaFeature: "Knowledge graph across your decks", note: "Launch pricing · during early access, plans come with your access code.", cta: "Request access" },
    ],
    more: "Top-ups of $10, $25, $50 or $100 on any plan; they never expire. Have a code?",
    moreLink: "Sign in and enter it →",
    fullLink: "Full pricing page →",
  },
  begin: {
    label: "Begin",
    eyebrow: "Begin",
    titleLead: "Bring your ", titleAccent: "next", titleTail: " deck.",
    lede: "Give the Director one sentence, or attach the report, spreadsheet or old deck it should start from. You approve the plan before a single slide is built.",
    build: "Request early access", realDeck: "Open a real deck first", experts: "Meet the experts",
    code: "Have an access code? Sign in with Google and enter it.",
  },
  pages: {
    bring: {
      title: "Bring what you have — Deckster",
      description: "Use your documents, spreadsheets and brand colours from the first brief. Turn past PowerPoints into reusable templates (beta).",
      hero: {
        label: "Bring", eyebrow: "Bring · sources, themes, templates",
        title: ["Bring what you've ", "already", " made."],
        lede: "Your best material is already on your laptop. Attach reports and spreadsheets as sources, set your brand colour as the theme, and — in beta — turn a past PowerPoint into a template you can reuse.",
        build: "Request early access", see: "See a template being made", cue: "How it works",
        trust: ["PDF, Word, PowerPoint and spreadsheets as sources", "Templates from .pptx (beta)", "Images kept at their own resolution"],
        roles: ["eyebrow", "title", "cards ×3", "hex cluster", "cards ×3", "takeaway band"],
        caption: "Read as a template · slide 4 of 16",
        process: ["Upload", "Read", "Use as it was", "New topic"],
      },
      template: {
        label: "Template", eyebrow: "From deck to template", feature: "templates",
        title: "A deck you've given becomes a template you can reuse.",
        lede: "Add a PowerPoint to your template library. Deckster reads every slide's layout, roles and theme, keeps its images at their own resolution, and opens it as an editable deck.",
        steps: [
          { number: "01 · ADD", title: "Upload a .pptx", body: "One PowerPoint at a time, up to 100 MB. PDF templates are not ready yet.", quote: "“Here's our June board pack.”" },
          { number: "02 · READ", title: "Layout, roles, theme", body: "Each slide is split into its parts — heading, cards, chart, takeaway — and the theme comes with it." },
          { number: "03 · USE AS IT WAS", title: "Edit the words", body: "Open it as a deck with the same layout and images, and change the text in place." },
          { number: "04 · NEW TOPIC", title: "Same layout, new story", feature: "templateNewTopic", body: "Describe a new presentation and the agents write it into your layout. Still being tuned." },
        ],
        captions: ["Your original", "Template · layout & roles", "Opened as an editable deck"],
        arrows: "→", roles: ["title", "cards", "hex cluster", "cards", "takeaway"],
      },
      library: {
        label: "Library", eyebrow: "Your template library", feature: "templates", title: "Templates that already look like you.",
        lede: "Every slide of a PowerPoint you add becomes a layout you can reuse. These eight came from one deck.",
        cards: [
          { slide: "deck-04", role: "hex cluster", title: "Six capabilities · honeycomb", detail: "from your deck · .pptx" },
          { slide: "deck-02", role: "steps ×5", role2: "columns ×5", title: "Five-step model · chevrons", detail: "from your deck · .pptx" },
          { slide: "deck-09", role: "statement", role2: "contact", title: "Closing · image hero", detail: "from your deck · .pptx" },
          { slide: "deck-06", title: "Decision forums · pyramid", detail: "from your deck · .pptx" },
          { slide: "deck-07", title: "Maturity ladder", detail: "from your deck · .pptx" },
          { slide: "deck-08", title: "Decision quadrant", detail: "from your deck · .pptx" },
          { slide: "deck-11", title: "Rollout timeline", detail: "from your deck · .pptx" },
          { slide: "deck-12", title: "Hiring funnel", detail: "from your deck · .pptx" },
        ],
      },
      knowledge: {
        label: "Sources", eyebrow: "Documents become sources",
        title: "Your files, read for facts. Charts that say where.",
        lede: "Attach PDFs, Word files, spreadsheets or decks to a brief. Their figures and claims are used first-hand; charts made from them say where their numbers came from. Switch on the knowledge graph and later decks can draw on them too.",
        checks: ["PDF · DOCX · PPTX · XLSX · CSV · TXT · MD", "Up to 5 files per deck, 100 MB each", "Spreadsheets become real charts and tables"],
        rows: [
          { kicker: "CHAT · RESEARCH MENU", title: "Web search · Deep research · Knowledge graph", body: "Choose per deck what the Researcher may use. Your attached files are always in.", feature: "sources" },
          { kicker: "SETTINGS · KNOWLEDGE GRAPH", title: "Build a knowledge graph across my decks", body: "Opt in once; browse entities and evidence on your Knowledge page; delete everything with one button.", feature: "knowledgeGraph" },
          { kicker: "PUBLISHED DECK · QUESTIONS", title: "What it can answer from", body: "Pick which of your documents a published deck may use. They are never named to the audience.", feature: "questions" },
        ],
      },
      inout: {
        label: "In & out", eyebrow: "In and out", title: "What comes in. What goes out.",
        lede: "No lock-in in either direction. Bring the files you have; leave with the formats your audience expects.",
        in: "In", out: "Out",
        inputs: [
          { kind: "PPTX", name: "Past presentations", detail: "· sources, and templates in beta" },
          { kind: "PDF", name: "Reports, studies, Word files", detail: "· read for facts and figures" },
          { kind: "DATA", name: "Spreadsheets and CSVs", detail: "· become real charts and tables" },
          { kind: "WEB", name: "Web search and deep research", detail: "· cited; estimates labelled as estimates" },
        ],
        outputs: [
          { kind: "PPTX", name: "PowerPoint, no watermark", detail: "· text and tables editable; charts and diagrams as images" },
          { kind: "PDF", name: "PDF", detail: "· every slide as you see it" },
          { kind: "LINK", name: "Published deck at deckster.xyz/p/…", detail: "· link or passcode, downloads you allow" },
          { kind: "VOICE", name: "Narrated deck that takes questions", detail: "· beta" },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Bring your ", "next", " deck."],
        lede: "Attach the report, spreadsheet or old deck it should start from. You approve the plan before a single slide is built.",
        build: "Request early access", code: "Have an access code? Sign in with Google and enter it.",
      },
    },
    present: {
      title: "Publish and present — Deckster",
      description: "Publish a deck with one button: a link or passcode, the downloads you allow, view counts. In beta: audience questions and narration.",
      hero: {
        label: "Present", eyebrow: "Present · publish, answer, narrate",
        title: ["Publish once. ", "Keep presenting."],
        lede: "Your deck gets a link you control today. In beta, it answers your audience's questions from your slides and documents, and can narrate itself in a stock voice you pick. Joining live meetings is planned.",
        build: "Request early access", see: "What publishing does", cue: "What publishing does",
        facts: ["Link or passcode", "PDF / PowerPoint downloads you allow", "View count and one-click republish", "Unpublish any time"],
        qaHeader: "Questions · Operating-model review", qaInput: "Ask about this deck…",
        sequence: [
          { who: "viewer", kicker: "Viewer", text: "How does the 48-hour rule handle vendor calls?" },
          { who: "deck", kicker: "Answer", text: "Up to £250k they sit with domain leadership; anything larger escalates after 48 hours.", source: "From slide 6 · tap to open it" },
          { who: "viewer", kicker: "Viewer", text: "Is the 11-day figure from this quarter?" },
          { who: "deck", kicker: "Answer", text: "Yes — it's the Q3 median across the four forums.", source: "From the presenter's background material" },
          { who: "viewer", kicker: "Viewer", text: "Who signs off budgets above £1m?" },
          { who: "deck", kicker: "Answer", text: "That isn't in this deck. I've passed it to the presenter.", source: "Sent to the owner's inbox" },
        ],
      },
      four: {
        label: "One button", eyebrow: "One button", title: "Publish does more than share.",
        lede: "What a published deck can do today, what is in beta, and what is planned.",
        cards: [
          { feature: "publish", title: "Publish", body: "A link at deckster.xyz/p/…, open to anyone with it, public, or behind a passcode. Allow or block PDF and PowerPoint downloads. See views; republish when the deck changes." },
          { feature: "questions", title: "Answer", body: "Viewers ask in the deck. Answers come from your slides and the documents you allow, with the slide to open. What it can't answer goes to your inbox; promote good answers to an FAQ." },
          { feature: "narration", title: "Narrate", body: "A script per slide, written to your time budget and recorded in one of nine stock voices. You see the price before recording; edit any line by hand." },
          { feature: "meetings", title: "Join meetings", body: "The deck joins a Zoom, Meet or Teams call as the presenter and takes questions there. Not built yet." },
        ],
        url: "deckster.xyz/p/", slug: "k3Tq9xV2aB",
        note: " · passcode · PDF download allowed · 128 views",
      },
      grounded: {
        label: "Grounded", eyebrow: "Grounded, not improvised", feature: "questions",
        title: "It answers what you'd answer. It passes on the rest.",
        lede: "Pick an answer style — Professional, Friendly, Concise or Technical. Style never changes what it is willing to say: anything outside your deck and allowed documents goes to your inbox.",
        tiers: [
          { name: "YOUR SLIDES", title: "Named, with a link", body: "“From slide 6” — the viewer can jump to it." },
          { name: "YOUR DOCUMENTS", title: "Used, never named", body: "The audience hears the fact, not the file: “From the presenter's background material.” You choose which documents it may use." },
          { name: "ANYTHING ELSE", title: "Passed to you", body: "“That isn't in this deck. I've passed it to the presenter.” The question waits in your inbox." },
        ],
        checks: ["Four answer styles", "Owner inbox: answer, publish to FAQ, or block", "Daily and monthly question caps", "You choose the sources"],
      },
      time: {
        label: "Time budget", eyebrow: "Time is a budget", feature: "narration",
        title: "Questions don't make the talk overrun.",
        lede: "Narration is recorded in two cuts, sized to the session you set, with time held for questions. If the clock runs short, the rest of the deck switches to the short cut — and it tells the room.",
        rows: [
          { label: "Full cut", duration: "12:00" },
          { label: "Short cut", duration: "06:30" },
          { label: "With questions", duration: "12:00" },
        ],
        checks: ["Session length + time held for questions", "Switches to the short cut when needed", "Closes on time"],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Publish your ", "first", " deck."],
        lede: "Build it with the team, press one button, and share the link.",
        build: "Request early access", pricing: "See pricing",
      },
    },
    experts: {
      title: "Direct a team of experts — Deckster",
      description: "The Director plans your deck and waits for your yes; specialists research, write and design it; you edit any slide yourself.",
      hero: {
        label: "Experts", eyebrow: "Experts · human in the loop",
        title: ["Direct a team of ", "experts."],
        lede: "The Director plans the deck and hands each step to a specialist. You approve the plan and the outline, watch the build slide by slide, and edit anything yourself.",
        build: "Request early access", see: "See the loop", cue: "How the loop works",
        trust: ["Plan and outline wait for your yes", "Every finished slide stays editable"],
      },
      loop: {
        label: "The loop", eyebrow: "The loop", title: "Nothing gets built until you say yes.",
        lede: "Deckster is not a slot machine. It shows you the plan and the outline before it spends anything on slides — then every slide stays yours to change.",
        gates: [
          { number: "GATE 1 · THE PLAN", feature: "approvals", title: "Approve the story first", body: "The Director proposes sections and slide count: “Does this structure work for you?” Change it in plain English before a single slide exists.", quote: "“Cut it to eight slides. Lead with the 48-hour rule.”" },
          { number: "GATE 2 · THE OUTLINE", feature: "approvals", title: "See the shape, then commit", body: "An outline card for every slide — what it says and how it's laid out — before the full build. “Looks perfect!” or “Make some changes”.", quote: "“Slide 5 should be a chart, not a table.”" },
          { number: "THEN · EVERY SLIDE", feature: "approvals", title: "Edit at any altitude", body: "Click any text to edit it, refine a single chart or diagram, or add a slide. The rest of the deck stays as it is.", quote: "“Make this chart a waterfall.”" },
        ],
        checks: [
          { text: "Watch the build, slide by slide" },
          { text: "Pause or stop a build", feature: "buildControl" },
          { text: "Finished slides are kept if you stop" },
        ],
      },
      team: {
        label: "The team", eyebrow: "Meet the team", title: "Specialists, not a one-size-fits-all model.",
        you: "you", producer: "executive producer", director: "Director",
        directorRole: "· plans the deck, picks the specialist for each step, keeps the through-line — and reports to you",
        agents: [
          { name: "Researcher", bold: "The investigator.", body: " Your files and the open web. Cites what it uses; marks estimates as estimates.", color: "#60a5fa" },
          { name: "Content Generator", bold: "The storyteller.", body: " Headlines, body, bullet hierarchies and speaker notes, tuned to your audience.", color: "#fb923c" },
          { name: "Visualizer", bold: "The designer.", body: " Picks the chart, builds the diagram, lays out the infographic — on one colour system.", color: "#f472b6" },
          { name: "Theme Builder", bold: "The stylist.", body: " Palette and type from a preset or your brand colour, applied to every slide.", color: "#22d3ee" },
          { name: "Slide Composer", bold: "The conductor.", body: " Builds each slide's layout and focus, and can compose one new slide into a deck with its neighbours in mind.", color: "#facc15" },
          { name: "Element Generator", bold: "The builder.", body: " Text boxes, metrics, tables, icons, charts and diagrams — refined one at a time when you ask.", color: "#c084fc" },
        ],
      },
      guardrails: {
        label: "Guardrails", eyebrow: "Guardrails", title: "Four things the team will never do.",
        cards: [
          { number: "01", title: "Build without your yes", body: "No slide is built before you approve the plan. Every finished slide stays editable." },
          { number: "02", title: "Pass off a guess as a fact", body: "Charts say where their numbers came from — a source, “User-provided data”, or “Illustrative” when no real data exists." },
          { number: "03", title: "Name your private files", body: "A published deck may use your uploads to answer — it never tells the audience they exist." },
          { number: "04", title: "Hide what it's doing", body: "You see each step as it happens — planning, research, each slide — and can pause or stop a build in beta." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Take the ", "chair."],
        lede: "One sentence to the Director is enough to start. Attach your documents and it starts further along.",
        build: "Request early access", bring: "Bring your material",
      },
    },
    pricing: {
      metadata: {
        title: "Pricing — Deckster",
        description: "Deckster is in early access. Launch pricing $20, $50 and $100 a month, differing by how much you can build; top-ups never expire; no watermark.",
      },
      start: {
        label: "Pricing",
        eyebrow: "Pricing · early access",
        title: "Priced for how you ",
        titleAccent: "present.",
        lede: "Deckster is in early access: sign in with Google and enter your access code, or ask for one. Plans differ by how much you can build each month.",
        cue: "Compare the plans",
        tiers: [
          {
            id: "starter",
            name: "Starter",
            price: "$20",
            suffix: "/ month",
            blurb: "For a deck every week or two.",
            features: [
              "The whole builder: research, your files, charts, diagrams, infographics",
              "PowerPoint & PDF export, no watermark",
              "Publish with a link or passcode",
              "$20 of building each month",
            ],
            note: "Launch pricing · during early access, plans come with your access code.",
            action: "Request access",
          },
          {
            id: "pro",
            tag: "Most popular",
            name: "Pro",
            price: "$50",
            suffix: "/ month",
            blurb: "For people who present every week.",
            features: [
              "Everything in Starter, plus:",
              "$50 of building each month",
              "Room for research-heavy decks",
            ],
            note: "Launch pricing · during early access, plans come with your access code.",
            action: "Request access",
          },
          {
            id: "premium",
            name: "Max",
            price: "$100",
            suffix: "/ month",
            blurb: "For people who present as their core work.",
            features: [
              "Everything in Pro, plus:",
              "$100 of building each month",
              "Knowledge graph across your decks",
            ],
            betaFeature: "Knowledge graph across your decks",
            note: "Launch pricing · during early access, plans come with your access code.",
            action: "Request access",
          },
        ],
      },
      matrix: {
        label: "Compare",
        eyebrow: "Plan by plan",
        title: "What each plan includes.",
        headings: ["Capability", "Starter", "Pro", "Max"],
        included: "Included", notIncluded: "Not included",
        rows: [
          { name: "Build", detail: " — plan, outline and slides with the Director; every element type", values: [true, true, true] },
          { name: "Research", detail: " — web search, cited on the slide", values: [true, true, true] },
          { name: "Your files", detail: " — PDFs, Word, spreadsheets and decks as sources", values: [true, true, true] },
          { name: "Themes", detail: " — presets, your brand colour, a saved standard theme", values: [true, true, true] },
          { name: "Export", detail: " — PowerPoint & PDF, no watermark", values: [true, true, true] },
          { name: "Publish", detail: " — link or passcode, downloads you allow", values: [true, true, true] },
          { name: "Building each month", detail: " — top up any time", values: ["$20", "$50", "$100"] },
          { name: "Knowledge graph", detail: "", feature: "knowledgeGraph", values: [false, false, true] },
          { name: "Questions & narration", detail: " on published decks", feature: "questions", note: "Uses your monthly building allowance; included on every plan" },
        ],
      },
      faq: {
        label: "Questions",
        eyebrow: "Top-ups & questions",
        title: "Need more in a busy month?",
        lede: "Top up $10, $25, $50 or $100 on any plan. Top-ups never expire. A long, research-heavy deck uses more than a short update.",
        questions: [
          { question: "How do I get in?", answer: "Sign in with Google. With an access code you can start right away; without one, you join the early-access queue." },
          { question: "What counts as usage?", answer: "The Director's planning and writing, slide building, narration recordings and audience answers. Each plan includes a monthly amount, with a daily share so one day can't use it all." },
          { question: "Where do my files go?", answer: "They are stored in your account and read by the AI models that build your deck (Google and OpenRouter-hosted models). They are never shown to your audience by name. You can delete your knowledge graph with one button; deleting a file removes it from your list." },
          { question: "Is there a watermark?", answer: "No. PowerPoint and PDF exports are clean on every plan. In PowerPoint, text and tables stay editable; charts and diagrams arrive as images." },
          { question: "Can my team share templates?", answer: "Not yet — templates and themes are personal for now." },
          { question: "What's in beta?", answer: "Audience questions, narration, the knowledge graph and templates from your own decks. Beta features may change." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Start with what you ", titleAccent: "have.",
        lede: "A report you already wrote is a fine first brief. So is a single sentence.",
        build: "Request access", bring: "Bring your material",
      },
    },
    about: {
      metadata: {
        title: "About — Deckster",
        description: "Deckster keeps you in the loop: your yes before anything is built, your sources on the charts, and a public list of what's live, in beta and planned.",
      },
      start: {
        label: "About", eyebrow: "Our story", title: "We're keeping the human in the ", titleAccent: "loop.",
        lede: "Deckster started from a simple conviction: a deck should come from a conversation, not a blank slide and a lost evening. It grew into a second one — that the best decks come from a team that shows its work and asks before it commits.",
        trust: ["Your yes before anything is built", "A public list of what works today"],
        cue: "What we believe",
        images: [9, 1, 4],
      },
      principles: {
        label: "Principles", eyebrow: "What we believe", title: "Three principles, every release.",
        cards: [
          { number: "01", title: "Your yes, every time", body: "Automation that asks is not slower — it is trustworthy. The plan and the outline wait for you, and every slide stays yours to edit." },
          { number: "02", title: "Your sources, shown", body: "Charts say where their numbers came from. Estimates are labelled as estimates. Your files are never named to your audience." },
          { number: "03", title: "Nothing is a black box", body: "You see each step of the build as it happens, and you can take the wheel on the canvas at any time." },
        ],
      },
      story: {
        label: "Status", eyebrow: "Where Deckster is today",
        title: "What's live, what's in beta, what's next.",
        lede: "We'd rather tell you exactly what works. This list changes as features ship.",
        columns: [
          { status: "live", items: ["Plan and outline approval before the build", "Edit any text; refine any chart, diagram or infographic", "Research from the web and your files, with sources on charts", "Theme presets, your brand colour, a saved standard theme", "PowerPoint & PDF export, no watermark", "Publish with a link or passcode, downloads you allow"] },
          { status: "beta", items: ["Audience questions on published decks, with your inbox", "Narration in one of nine stock voices, fitted to your time", "Knowledge graph across your decks", "Template library from your own PowerPoints", "Watch, pause or stop a build"] },
          { status: "planned", items: ["Switch a finished deck to a new theme", "Templates from PDFs; a new topic in your own layout", "The deck joins Zoom, Meet or Teams", "Team workspaces and shared templates"] },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Come build ", titleAccent: "with", titleTail: " us.",
        lede: "Try it on a deck you need this month. Tell us what the team got wrong — that is how it gets better.",
        build: "Request early access", email: "hello@deckster.xyz",
      },
    },
    learn: {
      metadata: {
        title: "Learn — Deckster",
        description: "Learn Deckster at your altitude: talk to the Director about the deck, compose one slide, or refine one element.",
      },
      start: {
        label: "Learn", eyebrow: "Learn", title: "Learn at your ", titleAccent: "altitude.",
        lede: "Everything in Deckster happens at one of three levels. Pick the one you're working at.",
        cards: [
          { name: "Deck", title: "Talk to the Director", body: "Briefs, plans, outlines, research options, themes, export. The whole-deck conversation.", example: "“Build a 16-slide review from my board pack.”", tags: ["Quick start", "Your first deck", "Research options"] },
          { name: "Slide", title: "Compose one slide", body: "Add or refine a single slide in any deck, with its neighbours as context. Layout, density, focus.", example: "“Add a slide after 4 comparing latency by team.”", tags: ["Slide panel", "Refine in place", "Layouts"] },
          { name: "Element", title: "Refine one piece", body: "Charts, tables, metrics, diagrams, infographics, text — change one without touching the rest.", example: "“Make this chart a waterfall.”", tags: ["Refine element", "Chart types", "Editing on canvas"] },
        ],
        cue: "Your first deck",
      },
      first: {
        label: "First deck", eyebrow: "Your first deck", title: "Five steps, one evening back.",
        steps: [
          { number: "01 · BRING", title: "Attach what you have", body: "A report, a spreadsheet, last quarter's deck. Optional — but it makes everything after more yours." },
          { number: "02 · BRIEF", title: "Tell the Director", body: "One sentence or a full brief. Choose web search, deep research or your knowledge graph." },
          { number: "03 · APPROVE", title: "Say yes to the plan", body: "Sections and slide count, then the outline. Change anything in plain English." },
          { number: "04 · REFINE", title: "Edit at any altitude", body: "Edit text on the canvas, refine a chart or diagram, add a slide — the rest stays intact." },
          { number: "05 · SHIP", title: "Export or publish", body: "PowerPoint, PDF — or a link with a passcode and the downloads you allow." },
        ],
      },
      guides: {
        label: "Guides", eyebrow: "Guides & help", title: "Stuck? Get unblocked.",
        cards: [
          { tag: "Getting started", title: "Quick start · Your first presentation", body: "The two reads for a first session.", href: "/docs/getting-started/quick-start-guide" },
          { tag: "Builder guide", title: "Chat · Editing slides · Exports", body: "Every panel in the builder.", href: "/docs/builder-guide/chat-interface" },
          { tag: "Help", title: "Help centre & FAQ", body: "Answers, plus support@deckster.xyz.", href: "/help" },
          { tag: "Guide coming", title: "Templates · Knowledge graph", body: "For the beta features." },
          { tag: "Guide coming", title: "Publishing · Questions · Narration", body: "What a published deck can and can't say." },
          { tag: "Guide coming", title: "Element reference", body: "Every chart, diagram and infographic type." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Ship your first deck ", titleAccent: "today.",
        build: "Request early access", bring: "Bring your material",
      },
    },
  },
} as const

/** Public image names are design slots; some contain a different source-deck slide. */
export const SHOWCASE_SLOTS = {
  1: { slide: 1, title: "A new operating model moves" },
  2: { slide: 2, title: "Driving Business Agility through a Five-Step Model" },
  3: { slide: 3, title: "Managing the Ownership Chain for Product Changes" },
  4: { slide: 11, title: "Strengthening the Six Capabilities of Modern Delivery" },
  5: { slide: 5, title: "A Weekly Loop to Replace the Board" },
  6: { slide: 6, title: "Optimizing Decision Forums and Governance Cadence" },
  7: { slide: 7, title: "Teams Climb Five Levels of Delivery Maturity" },
  8: { slide: 9, title: "Where each decision should live" },
  9: { slide: 16, title: "Next Wave Lowers Later Costs" },
  10: { slide: 10, title: "Four Core Pillars of the Operating Model" },
  11: { slide: 12, title: "The rollout runs from June 2026 to June 2027" },
  12: { slide: 14, title: "Hiring Worked: Eleven Engineers Joined Last Quarter" },
} as const

export function showcaseAlt(slot: number, fallbackTitle?: string) {
  const source = SHOWCASE_SLOTS[slot as keyof typeof SHOWCASE_SLOTS]
  return `Slide ${source?.slide ?? slot} of the showcase deck: ${source?.title ?? fallbackTitle ?? "Untitled slide"}`
}
