import { AGENT_TEAM, type AgentId } from "@/lib/marketing/homepage-v2-content"

/** Copy for marketing v3. Keep wording in sync with design-marketing-v3/*.html. */
const agentColor = (id: AgentId) => AGENT_TEAM.find((agent) => agent.id === id)!.color

export const V3_CONTENT = {
  metadata: {
    title: "Deckster — Your knowledge. Your decks. Your voice.",
    description:
      "Deckster turns what you already have — documents, past presentations, your brand — into decks built by a team of AI specialists you direct. Then the deck presents itself.",
  },
  nav: [
    { label: "Build", href: "/#zoom" },
    { label: "Bring", href: "/bring" },
    { label: "Present", href: "/present" },
    { label: "Experts", href: "/experts" },
    { label: "Pricing", href: "/pricing" },
  ],
  header: {
    home: "Deckster home",
    wordmark: "deckster",
    signIn: "Sign in",
    build: "Build a deck",
  },
  footer: {
    copyright: "© 2026 deckster · Your knowledge. Your decks. Your voice.",
    links: [
      { label: "Bring", href: "/bring" },
      { label: "Present", href: "/present" },
      { label: "Experts", href: "/experts" },
      { label: "Pricing", href: "/pricing" },
      { label: "Learn", href: "/learn" },
      { label: "About", href: "/about" },
      { label: "Privacy", href: "/legal/privacy" },
      { label: "Terms", href: "/legal/terms" },
    ],
  },
  start: {
    label: "Start",
    eyebrow: "AI presentation studio · you stay in the loop",
    title: ["Your knowledge.", "Your decks.", "Your voice."],
    lede:
      "Deckster turns what you already have — documents, past presentations, your brand — into decks built by a team of AI specialists. You direct every step. When it's done, the deck can present itself, in a voice you choose.",
    build: "Build a deck",
    drop: "Drop a deck, get a template",
    trust: [
      "PPTX & PDF in",
      "PPTX & PDF out, no watermark",
      "Charts, diagrams, infographics built in",
      "Every step needs your yes",
    ],
    cursor: "you",
    request: "make the chart a waterfall — use our Q3 numbers",
    agent: "Element Composer · ",
    agentBold: "waterfall rendered",
    agentSource: " · source: Q3 board pack, p.7",
    cue: "See how it works",
  },
  zoom: {
    label: "Precision",
    eyebrow: "Precision",
    title: "Control it at every altitude.",
    altitudes: ["Deck", "Slide", "Element"],
    foot: "Scroll to zoom in · deck → slide → element",
    tiles: [
      { slide: 1, tag: "01 · Title", title: "A new operating model moves" },
      { slide: 2, tag: "02 · How it works", title: "Driving Business Agility through a Five-Step Model" },
      { slide: 3, tag: "03", title: "Managing the Ownership Chain for Product Changes" },
      { slide: 4, tag: "04 · Analysis", title: "Strengthening the Six Capabilities of Modern Delivery" },
      { slide: 6, tag: "06", title: "Optimizing Decision Forums and Governance Cadence" },
      { slide: 7, tag: "07", title: "Teams Climb Five Levels of Delivery Maturity" },
      { slide: 8, tag: "08", title: "Where each decision should live" },
      { slide: 9, tag: "16 · Closing", title: "Next Wave Lowers Later Costs" },
    ],
    exchanges: [
      {
        altitude: "deck",
        who: "You → Director",
        request: "“Build a 16-slide operating-model review from my Q3 board pack.”",
        response:
          "Director · plan drafted — 3 sections, 16 slides. Researcher on your uploads, Visualizer on the throughput data. Waiting for your approval.",
        action: "Approve plan",
        secondary: "Edit plan",
      },
      {
        altitude: "slide",
        who: "You → Slide Composer",
        request: "“Add a slide after 4 that compares decision latency by team.”",
        response:
          "Slide Composer · researched from your board pack, composed in the deck's theme, inserted at 5. Neighbours read for continuity.",
        action: "Keep it",
        secondary: "Refine",
      },
      {
        altitude: "element",
        who: "You → Element Composer",
        request: "“Make this chart a waterfall and cite the source.”",
        response:
          "Element Composer · waterfall rendered · 6 steps · source stamped: Q3 board pack, slide 7 — yours.",
        action: "Regenerate",
        secondary: "Try another",
      },
    ],
    slide: {
      eyebrow: "ANALYSIS",
      title: "Decision latency by ",
      titleAccent: "team",
      elements: {
        title: "Title",
        metrics: "Metrics ×3",
        chart: "Chart",
        text: "Text ×2",
        takeaway: "Takeaway",
      },
      metrics: [
        { value: "11 days", label: "Median decision" },
        { value: "48 h", label: "Target rule" },
        { value: "−23%", label: "Throughput gap" },
      ],
      chartTitle: "Days from request to decision, by team",
      waterfallTitle: "Where the 11 days go",
      chartSub: "Q3 · six delivery teams · your board pack",
      bars: [
        { height: 70, base: 0, waterfallHeight: 36.4, value: "14", waterfallValue: "+4.0", label: "Platform", waterfallLabel: "Approval wait" },
        { height: 55, base: 36.4, waterfallHeight: 27.3, value: "11", waterfallValue: "+3.0", label: "Payments", waterfallLabel: "Handoffs" },
        { height: 85, base: 63.7, waterfallHeight: 18.2, value: "17", waterfallValue: "+2.0", label: "Risk", waterfallLabel: "Rework" },
        { height: 45, base: 81.9, waterfallHeight: 13.6, value: "9", waterfallValue: "+1.5", label: "Data", waterfallLabel: "Unsequenced starts" },
        { height: 40, base: 95.5, waterfallHeight: 4.5, value: "8", waterfallValue: "+0.5", label: "Mobile", waterfallLabel: "Other" },
        { height: 60, base: 0, waterfallHeight: 100, value: "12", waterfallValue: "11.0", label: "Ops", waterfallLabel: "Total" },
      ],
      sourceLabel: "SOURCE",
      source: "Q3 board pack · slide 7 · yours",
      sides: [
        {
          title: "What we saw",
          body: "Approvals wait a median of four days at domain level. Six in ten stalls were waiting on a decision already taken elsewhere.",
        },
        {
          title: "What to do",
          body: "Move decision rights to the lowest safe level. Anything stuck longer than 48 hours escalates one rung — automatically.",
        },
      ],
      takeaway: "Decision latency — not capacity — is the binding constraint on delivery.",
      foot: "Fixing delivery without adding headcount",
      number: "5 / 16",
    },
  },
  bring: {
    label: "Bring",
    eyebrow: "Bring what you have",
    title: "Start from what you already have.",
    lede: "Nobody starts from zero. Your past decks, your documents and your brand are the raw material — Deckster turns them into templates, knowledge and themes you reuse on every deck after this one.",
    inputs: [
      { kind: "PPTX", name: "Q3 board pack.pptx", detail: "16 slides · presented in June" },
      { kind: "PDF", name: "Market study.pdf", detail: "48 pages · analyst report" },
      { kind: "BRAND", name: "Brand guide.pdf", detail: "palette · type · logo rules" },
    ],
    template: { title: "Template · Board pack", detail: "roles, ratios & theme — fill with new content", alt: "Slide 11 of the showcase deck: Strengthening the Six Capabilities of Modern Delivery" },
    knowledgeAsset: { title: "Knowledge · 1,284 facts", detail: "96 sources, all yours, all citable" },
    themeAsset: { title: "Theme · Northbank teal", detail: "palette + type + hero slides, as one bundle" },
    notes: [
      { title: "Decks become templates", body: "Drop a PPTX or PDF. It's deconstructed into roles, ratios and a theme — a template you fill with new content, in exactly your layout." },
      { title: "Documents become knowledge", body: "Facts pulled from your files are kept, linked and cited in the decks that follow. Your numbers, with your provenance — not the web's." },
      { title: "Brands become themes", body: "Palette, type and hero slides travel together as a bundle. Switch a whole deck to it — even after it's built." },
    ],
  },
  knowledge: {
    label: "Knowledge",
    eyebrow: "Knowledge graph",
    title: "Every deck you make teaches the next one.",
    lede: "Uploads, research passes and finished decks become a graph that is yours. When the Researcher runs, it checks your graph first — and cites your own documents before it cites the web.",
    legend: { research: "from research", documents: "from your documents" },
    stats: { decks: "decks", facts: "facts", sources: "sources" },
    citation: {
      web: { label: "From the web", value: "Median approval latency in mid-size banks: 6.2 days", source: "Source: industry survey, 2025 · estimated" },
      graph: { label: "From your graph", value: "Median approval latency at Northbank: 11 days", sourceLead: "Source: ", sourceStrong: "Q3 board pack, slide 7 · yours" },
    },
    checks: ["Yours alone", "Purge anytime", "Export anytime", "Never named to your audience"],
  },
  experts: {
    label: "Experts",
    eyebrow: "Human in the loop",
    title: "You direct. Specialists build.",
    lede: "Eight agents, each with one craft. The Director runs them; you run the Director. Nothing ships without your yes — and you can pause, steer or take over at any moment.",
    you: { name: "you", role: "executive producer · the human in the loop" },
    director: { name: "Director", role: "· plans, routes, checks coherence — reports to you" },
    agents: [
      { id: "researcher", name: "Researcher", role: "your files, then the web", color: agentColor("researcher") },
      { id: "analyst", name: "Analyst", role: "the insight in the numbers", color: agentColor("analyst") },
      { id: "content_generator", name: "Content", role: "headlines, body, notes", color: agentColor("content_generator") },
      { id: "visualizer", name: "Visualizer", role: "charts, diagrams, infographics", color: agentColor("visualizer") },
      { id: "theme_builder", name: "Theme Builder", role: "palette, type, heroes", color: agentColor("theme_builder") },
      { id: "slide_composer", name: "Slide Composer", role: "pacing, balance, focus", color: agentColor("slide_composer") },
      { id: "element_generator", name: "Element Gen.", role: "the atoms of each slide", color: agentColor("element_generator") },
    ],
    gates: [
      { number: "1", name: "Plan", action: "→ your yes" },
      { number: "2", name: "Strawman", action: "→ your yes" },
      { number: "3", name: "Every slide", action: "→ your edit" },
    ],
    loop: {
      bar: "Chain of thought · slide 5 of 16",
      live: "Live · chain of thought",
      paused: "Paused by you",
      pause: "Pause",
      resume: "Resume",
      steer: "Steer",
      placeholder: "Use our numbers, not industry averages",
      inputLabel: "Steer the team",
      pauseLine: { who: "you", text: "Pause. Let me look at slide 5 first." },
      resumeLine: { who: "director", text: "Resuming — picking up at slide 6." },
      steerReplies: [
        { who: "director", text: "Understood — re-routing to your uploads, web figures demoted to \"estimated\"." },
        { who: "researcher", text: "Re-reading board pack slides 7–9 for the latency series" },
      ],
      script: [
        { kind: "k", who: "director", text: "Plan approved by you · 16 slides · routing work" },
        { kind: "a", who: "researcher", text: "Reading your board pack (16 slides) before the web" },
        { kind: "a", who: "researcher", text: "Found decision-latency figures on slide 7 — keeping provenance" },
        { kind: "a", who: "analyst", text: "Median 11 days vs 48h target · 23% throughput gap" },
        { kind: "a", who: "theme", text: "Applying Northbank teal bundle · heroes H1/H2/H3 locked" },
        { kind: "a", who: "content", text: "Drafting slide 5 headline: \"Decision latency by team\"" },
        { kind: "a", who: "visualizer", text: "Bar chart · 6 teams · source stamped from your upload" },
        { kind: "a", who: "composer", text: "Slide 5 balanced · focal element = chart · white space ok" },
        { kind: "a", who: "director", text: "Slide 5 ready for your review" },
        { kind: "a", who: "researcher", text: "Web pass: 3 external benchmarks, marked estimated" },
        { kind: "a", who: "analyst", text: "Rework accounts for 2.0 of the 11 days" },
        { kind: "a", who: "composer", text: "Slide 6 · two-column · table + takeaway band" },
      ],
    },
  },
  themes: {
    label: "Themes",
    eyebrow: "Themes & templates",
    title: "Change the whole look after it's built.",
    lede: "A theme is a bundle — palette, type, toppings and hero slides — applied deck-wide. Switch it after generation. Build your own in Theme Studio. Lock any deck's design and reuse it as a template.",
    variants: [
      {
        id: "dark", name: "Dark minimal", note: "same deck · same words · new bundle",
        swatches: ["#0f2027", "#1e6f79", "#d3eef2"],
        images: ["theme-hero-dark-slide-01.jpg", "theme-hero-dark-slide-02.jpg", "theme-old-deck-04.jpg"],
      },
      {
        id: "vibrant", name: "Vibrant", note: "warm metallics on ink",
        swatches: ["#2a2158", "#b58c4a", "#e9d8ff"],
        images: ["theme-hero-vibrant-slide-01.jpg", "theme-hero-vibrant-slide-02.jpg", "theme-deckA-slide-01.jpg"],
      },
      {
        id: "abstract", name: "Abstract", note: "painterly heroes, quiet body slides",
        swatches: ["#5f7f8a", "#c9a227", "#8b2252"],
        images: ["theme-abstract-slide-01.jpg", "theme-abstract-slide-02.jpg", "theme-old-deck-02.jpg"],
      },
      {
        id: "industrial", name: "Industrial", note: "steel, signal orange, grid",
        swatches: ["#1b1b1b", "#6b7280", "#f59e0b"],
        images: ["theme-industrial-slide-01.jpg", "theme-industrial-slide-02.jpg", "theme-deckB-slide-01.jpg"],
      },
    ],
    studio: {
      title: "Theme Studio",
      lead: "Start from a preset or your brand guide. Tune palette, type and hero style, then save the bundle. Any deck can switch to it later — now showing ",
    },
  },
  present: {
    label: "Present",
    eyebrow: "Present",
    title: "Publish it. Then let it present itself.",
    lede: "One button gives your deck a link, a narrator and a memory. It presents in a voice you choose, answers the room's questions from your own sources, and shows up in as many rooms as you like — at the same time.",
    player: {
      urlPrefix: "deckster.xyz/p/", urlSlug: "operating-model-review", access: "● invite-only · downloads on",
      caption: "Narrating · slide 4 of 16", time: "04:12 left", voice: "◉ chosen voice",
    },
    qa: {
      live: "Live", title: "Audience Q&A", input: "Ask the deck anything…",
      sequence: [
        { who: "viewer", kicker: "Zurich · board room", text: "How does the 48-hour rule handle vendor calls?" },
        { who: "deck", kicker: "Answered aloud · chosen voice", text: "Vendor calls sit with Domain Leadership up to £250k. Anything larger escalates one rung automatically after 48 hours.", source: "Grounded in slide 6 · spoken, not read" },
        { who: "viewer", kicker: "New York · investor call", text: "Is the 11-day figure this quarter’s?" },
        { who: "deck", kicker: "Answered aloud · chosen voice", text: "Yes — Q3, the median across all four forums.", source: "Source kept private · your board pack" },
        { who: "viewer", kicker: "Bengaluru · all-hands", text: "What changes for pod stand-ups?" },
        { who: "deck", kicker: "Answered aloud · chosen voice", text: "Pods get ship decisions up to £50k without waiting for a forum.", source: "Grounded in slide 6" },
      ],
    },
    ladder: [
      { status: "live", statusLabel: "Live", text: "Publish & share — link, access modes, PDF/PPTX downloads you control" },
      { status: "live", statusLabel: "Live", text: "Viewers ask, the deck answers — grounded only in what you allow" },
      { status: "build", statusLabel: "In build", text: "Narration in a voice you choose — full and compressed cuts, tone presets" },
      { status: "next", statusLabel: "Next", text: "Joins Zoom, Meet and Teams — many rooms, one you" },
    ],
  },
  gallery: {
    label: "Gallery",
    eyebrow: "What they build",
    title: "Every shape your idea fits into.",
    lede: "Charts, diagrams, infographics, tables — describe it, and the Visualizer builds the right one. Regenerate any single one without touching the rest of the slide.",
    counts: [
      { value: 9, label: "element types" },
      { value: 18, label: "chart variants" },
      { value: 8, label: "diagram patterns" },
      { value: "∞", label: "infographics" },
    ],
    rows: [
      [
        ["Text box", "el"], ["Metrics", "el"], ["Table", "el"], ["Image", "el"], ["Icon & label", "el"], ["Shape", "el"],
        ["Line", "ch"], ["Vertical bar", "ch"], ["Horizontal bar", "ch"], ["Pie", "ch"], ["Doughnut", "ch"], ["Scatter", "ch"], ["Bubble", "ch"], ["Radar", "ch"], ["Polar area", "ch"], ["Area", "ch"], ["Stacked area", "ch"], ["Grouped bar", "ch"], ["Stacked bar", "ch"], ["Waterfall", "ch"], ["Treemap", "ch"],
      ],
      [
        ["Code display", "dg"], ["Cloud architecture", "dg"], ["Logical architecture", "dg"], ["Data architecture", "dg"], ["Idea board", "dg"], ["Kanban", "dg"], ["Gantt", "dg"], ["Chevron maturity", "dg"],
        ["Pyramid", "in"], ["Funnel", "in"], ["Hexagon spread", "in"], ["Concentric circles", "in"], ["Cycle", "in"], ["Timeline", "in"], ["Ladder", "in"], ["Rocket", "in"], ["Tree", "in"], ["Ship", "in"], ["Rail", "in"], ["Anything you describe", "inf"],
      ],
      [
        ["Infographic", "el"], ["Diagram", "el"], ["Stacked bar", "ch"], ["Gantt", "dg"], ["Cycle", "in"], ["Treemap", "ch"], ["Kanban", "dg"], ["Pyramid", "in"], ["Table", "el"], ["Waterfall", "ch"], ["Cloud architecture", "dg"], ["Timeline", "in"], ["Metrics", "el"], ["Radar", "ch"], ["Anything you describe", "inf"],
      ],
    ],
  },
  pricingHome: {
    label: "Pricing",
    eyebrow: "Pricing",
    title: "Priced for how you present — not how many seats.",
    lede: "Three tiers, top-ups anytime. What you bring — files, research, your knowledge graph — is what unlocks the next tier.",
    tiers: [
      { id: "starter", name: "Starter", price: "$20", suffix: "per user / mo", blurb: "Everything to ship a polished deck on your own.", features: ["Director, Content, Visualizer, Slide Composer, Theme Builder", "All chart, diagram and infographic types", "Custom themes", "PowerPoint & PDF export — no watermark", "Top-up credits anytime"], note: "Generous monthly credits for typical workloads.", cta: "Get started" },
      { id: "pro", name: "Pro", price: "$50", suffix: "per user / mo", blurb: "For people who present every week — with research.", features: ["Everything in Starter, plus:", "Researcher: live data from the open web", "Upload your own files as source material", "Analyst: finds the story in your numbers", "Higher monthly credit allowance"], note: "Suited to research-heavy and frequent presenters.", cta: "Get started", tag: "Most popular" },
      { id: "max", name: "Max", price: "$100", suffix: "per user / mo", blurb: "For people who present as their core work.", features: ["Everything in Pro, plus:", "Knowledge Graph: agents learn your domain across decks", "Priority generation queue", "Highest monthly credit allowance"], note: "Built for the heaviest, most demanding workflows.", cta: "Get started" },
    ],
    more: "Need more in a busy month? Top-ups on every tier, no commitment.",
    moreLink: "Full pricing page →",
  },
  begin: {
    label: "Begin",
    eyebrow: "Begin",
    titleLead: "Bring your ", titleAccent: "first", titleTail: " deck.",
    lede: "Drop a presentation you've already given. Watch it become a template, a theme and a head start on the next one.",
    drop: { iconTop: "PPTX", iconBottom: "PDF", title: "Drop a .pptx or .pdf here", description: "or start from a single sentence — the Director takes it from there." },
    build: "Build a deck", experts: "Meet the experts",
  },
  pages: {
    bring: {
      title: "Bring what you have — Deckster",
      hero: {
        label: "Bring", eyebrow: "Bring · templates, knowledge, themes",
        title: ["Bring what you've ", "already", " made."],
        lede: "Your best decks are already on your laptop. Drop one in and get a reusable template, a theme and a knowledge base that grows with every deck you make after it.",
        drop: "Drop a deck", see: "See a template being made", cue: "How it works",
        trust: ["PPTX & PDF accepted", "Images kept, cropped at native resolution", "You review every role before it's saved"],
        roles: ["eyebrow", "title", "cards ×3", "hex cluster", "cards ×3", "takeaway band"],
        caption: "Deconstructed · slide 4 of 16",
        process: ["Upload", "Deconstruct", "Your review", "Reuse"],
      },
      template: {
        label: "Template", eyebrow: "From deck to template",
        title: "A deck you've given becomes a template you can fill.",
        lede: "Not a screenshot. Not a theme guess. Every slide is read from first principles — roles, ratios, type, colour — and rebuilt as a structure your new content can pour into.",
        steps: [
          { number: "01 · UPLOAD", title: "Drop the file", body: "PPTX or PDF — one deck or your whole archive. Media is kept and cropped at native resolution.", quote: "“Here's our June board pack.”" },
          { number: "02 · DECONSTRUCT", title: "Read, not traced", body: "Each slide is split into containers and roles — heading, lede, card grid, chart, takeaway — with their ratios and the theme they imply." },
          { number: "03 · REVIEW", title: "You correct the roles", body: "The abstraction view shows what was understood. Fix any role it got wrong; it never saves without you.", quote: "“That band is a takeaway, not a footer.”" },
          { number: "04 · REUSE", title: "Fill it with new content", body: "Pick the template on your next brief. The agents write into your layout — same structure, same look, new story." },
        ],
        captions: ["Your original", "Template · roles & ratios", "New content, your layout"],
        arrows: "→", roles: ["title", "cards", "hex cluster", "cards", "takeaway"],
      },
      library: {
        label: "Library", eyebrow: "Your template library", title: "Templates that already look like you.",
        lede: "Presets are fine. The templates made from your own decks are the ones your audience already recognises.",
        filters: ["All", "From my decks", "Locked designs", "Presets", "Shared with me"],
        cards: [
          { slide: "deck-04", role: "hex cluster", title: "Operating model · capabilities", detail: "from your deck · 16 slides · navy" },
          { slide: "deck-02", role: "steps ×5", role2: "columns ×5", title: "Five-step model · chevrons", detail: "from your deck · 16 slides · navy" },
          { slide: "deck-09", role: "statement", role2: "contact", title: "Closing · image hero", detail: "locked design · reused 6×" },
          { slide: "deck-06", title: "Decision forums · pyramid", detail: "from your deck · 16 slides" },
          { slide: "theme-industrial-slide-01", title: "Title · Industrial", detail: "preset bundle" },
          { slide: "deck-07", title: "Maturity ladder", detail: "from your deck · 16 slides" },
          { slide: "theme-abstract-slide-02", title: "Problem · Abstract", detail: "preset bundle" },
          { slide: "deck-08", title: "Decision quadrant", detail: "shared with you · ops review" },
        ],
      },
      knowledge: {
        label: "Knowledge", eyebrow: "Documents become knowledge", title: "Your files, read once. Cited forever.",
        lede: "Every upload is read for facts, figures and claims. They join a graph that is yours alone — and the Researcher checks it before it checks the web.",
        sources: [
          { kind: "PPTX", name: "Q3 board pack.pptx", detail: "16 slides · read 2026-09-12", count: "312 facts" },
          { kind: "PDF", name: "Market study.pdf", detail: "48 pages · read 2026-09-14", count: "690 facts" },
          { kind: "XLSX", name: "Throughput by team.xlsx", detail: "6 sheets · read 2026-09-20", count: "282 facts" },
        ],
        legend: { research: "from research", documents: "from your documents" },
        stats: { decks: "decks", facts: "facts", sources: "sources" },
        toggles: [
          { label: "Use my graph on every research pass", value: "on" },
          { label: "Cite my documents before the web", value: "on" },
          { label: "Allow in published Q&A", value: "per deck" },
        ],
        purge: "PURGE", export: "EXPORT", ownership: "yours, always",
      },
      inout: {
        label: "In & out", eyebrow: "In and out", title: "What comes in. What goes out.",
        lede: "No lock-in in either direction. Bring the files you have; leave with the formats your audience expects.",
        in: "In", out: "Out",
        inputs: [
          { kind: "PPTX", name: "Past presentations", detail: "· become templates & knowledge" },
          { kind: "PDF", name: "Reports, studies, brand guides", detail: "· become knowledge & themes" },
          { kind: "DATA", name: "Spreadsheets and CSVs", detail: "· become grounded charts & tables" },
          { kind: "WEB", name: "Live web research", detail: "· cited, marked estimated where it is" },
        ],
        outputs: [
          { kind: "PPTX", name: "Editable PowerPoint", detail: "· no watermark" },
          { kind: "PDF", name: "Print-ready PDF", detail: "· high quality" },
          { kind: "LINK", name: "Published deck at deckster.xyz/p/…", detail: "· invite-only or public" },
          { kind: "VOICE", name: "Narrated cut with live Q&A", detail: "· in build" },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Bring your ", "first", " deck."],
        lede: "Drop a presentation you've already given. Watch it become a template, a theme and a head start on the next one.",
        fileKinds: ["PPTX", "PDF"], drop: "Drop a .pptx or .pdf here",
        hint: "or start from a single sentence — the Director takes it from there.",
      },
    },
    present: {
      title: "Present without being there — Deckster",
      hero: {
        label: "Present", eyebrow: "Present · publish, narrate, answer",
        title: ["Present without ", "being there."],
        lede: "Publish once. Your deck gets a link, a narrator and a memory — and answers your audience's questions aloud, in a voice you choose, while you are somewhere else entirely.",
        publish: "Publish a deck", see: "What one button does", cue: "One button, four things",
        trust: ["Invite-only, password or public", "Downloads you control", "Answers only from sources you allow"],
        qaHeader: "Audience Q&A · operating-model-review", qaInput: "Ask the deck anything…", live: "Live",
        sequence: [
          { who: "viewer", kicker: "Zurich · board room", text: "How does the 48-hour rule handle vendor calls?" },
          { who: "deck", kicker: "Answered aloud · chosen voice", text: "Vendor calls sit with Domain Leadership up to £250k. Anything larger escalates one rung automatically after 48 hours.", source: "Grounded in slide 6 · spoken, not read" },
          { who: "viewer", kicker: "New York · investor call", text: "Is the 11-day figure this quarter’s?" },
          { who: "deck", kicker: "Answered aloud · chosen voice", text: "Yes — Q3, the median across all four forums.", source: "Source kept private · your board pack" },
          { who: "viewer", kicker: "Bengaluru · all-hands", text: "What changes for pod stand-ups?" },
          { who: "deck", kicker: "Answered aloud · chosen voice", text: "Pods get ship decisions up to £50k without waiting for a forum.", source: "Grounded in slide 6" },
        ],
      },
      four: {
        label: "One button", eyebrow: "One button, four things", title: "Publish does more than share.",
        lede: "A published deck is a living thing: it has an address, a script, a voice and a memory of what it is allowed to say.",
        cards: [
          { status: "Live", title: "Publish", body: "A clean link at deckster.xyz/p/… Invite-only, password or public. PDF and PPTX downloads — each one gated by you." },
          { status: "In build", title: "Narrate", body: "A script per slide, pre-rendered in a voice you choose. Full and compressed cuts, four tone presets, and a closing you can jump to from anywhere." },
          { status: "Live", title: "Answer", body: "Viewers ask in the deck. It answers from the sources you allowed — spoken back in the voice you chose — and sends you what it couldn't answer." },
          { status: "Next", title: "Multiply", body: "Many rooms, one you. The deck joins Zoom, Meet and Teams as a presenter and takes questions in each room at once." },
        ],
        rooms: [
          { name: "Board room", detail: "Zurich · 14 viewers" },
          { name: "Investor call", detail: "New York · 6 viewers" },
          { name: "All-hands", detail: "Bengaluru · 212 viewers" },
        ],
        url: "deckster.xyz/p/", slug: "operating-model-review",
        roomNote: " · invite-only · downloads on · narrating slide 6 of 16 in three rooms at once",
      },
      grounded: {
        label: "Grounded", eyebrow: "Grounded, not improvised",
        title: "It answers what you'd answer. It passes on the rest.",
        lede: "Tone is yours to set — formal, warm, brisk, playful. Substance is not negotiable: a question outside your sources gets a polite “I'll pass that to the presenter” and lands in your inbox with the viewer's name.",
        tiers: [
          { name: "TIER 1 · PUBLIC WEB", title: "Cited by name", body: "“Median approval latency in mid-size banks is 6.2 days — industry survey, 2025.”" },
          { name: "TIER 2 · YOUR UPLOADS", title: "Used, never named", body: "The answer draws on your board pack; the audience hears the fact, not the file. Existence and title of private documents never leak." },
          { name: "TIER 3 · KNOWLEDGE GRAPH", title: "Off unless you say so", body: "Your graph stays out of published Q&A by default. Allow it per deck, per source." },
        ],
        checks: ["Four tone presets, one refusal threshold", "Owner inbox for the unanswered", "Every answer traceable to a slide or source", "Per-deck allow list of sources"],
      },
      time: {
        label: "Time budget", eyebrow: "Time is a budget", title: "Interruptions never overrun the talk.",
        lede: "Narration is pre-rendered in two cuts. When questions eat the clock, lower-priority slides compress first — and the closing can play from any point.",
        rows: [
          { label: "Full cut", duration: "12:00" },
          { label: "Compressed cut", duration: "06:30" },
          { label: "With 4 questions", duration: "12:00" },
        ],
        checks: ["Per-slide priority", "Closing playable from any point", "Degrades gracefully, never overruns"],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Publish your ", "first", " deck."],
        lede: "Build it with the team, press one button, and take the evening while it presents.",
        build: "Build a deck", pricing: "See pricing",
      },
    },
    experts: {
      title: "Direct a team of experts — Deckster",
      hero: {
        label: "Experts", eyebrow: "Experts · human in the loop",
        title: ["Direct a team of ", "experts."],
        lede: "Eight specialists, one craft each. The Director runs them; you run the Director. You see every thought as it happens — and you can pause, steer or take over at any moment.",
        build: "Build a deck", see: "See the loop", cue: "How the loop works",
        trust: ["Plan, strawman and every slide wait for your yes", "Chain of thought visible, not hidden"],
      },
      loop: {
        label: "The loop", eyebrow: "The loop", title: "Three gates. Nothing passes without you.",
        lede: "Deckster is not a slot machine. It is a team that shows its work and asks before it commits — the way a good team does.",
        gates: [
          { number: "GATE 1 · THE PLAN", title: "Approve the story first", body: "The Director proposes sections, slide count and who does what. Change any of it in plain English before a single slide exists.", quote: "“Cut it to eight slides. Lead with the 48-hour rule.”" },
          { number: "GATE 2 · THE STRAWMAN", title: "See the shape, then commit", body: "A quick draft of every slide — content, layout, theme — before the expensive pass. Accept, reshuffle or send it back.", quote: "“Slide 5 should be a chart, not a table.”" },
          { number: "GATE 3 · EVERY SLIDE", title: "Edit at any altitude", body: "Regenerate a slide, a single element, or change a word by hand on the canvas. The team keeps everything else intact.", quote: "“Make this chart a waterfall.”" },
        ],
        actions: [
          { icon: "⏸", name: "Pause", detail: " — stop the team mid-thought" },
          { icon: "↪", name: "Steer", detail: " — redirect with one sentence" },
          { icon: "✎", name: "Take over", detail: " — edit the canvas yourself" },
        ],
      },
      team: {
        label: "The eight", eyebrow: "Meet the eight", title: "Specialists, not a one-size-fits-all model.",
        you: "you", producer: "executive producer", director: "Director",
        directorRole: "· plans the deck, picks the specialist for each step, keeps the through-line — and reports to you",
        agents: [
          { name: "Researcher", bold: "The investigator.", body: " Your files and your graph first, then the open web. Cites every number; flags conflicts; marks estimates as estimates.", color: "#60a5fa" },
          { name: "Analyst", bold: "The insight finder.", body: " Trends, gaps and outliers — and the one-line takeaway your audience actually needs.", color: "#34d399" },
          { name: "Content Generator", bold: "The storyteller.", body: " Headlines, body, bullet hierarchies, speaker notes — in your tone, tuned to the audience.", color: "#fb923c" },
          { name: "Visualizer", bold: "The designer.", body: " Picks the chart, builds the diagram, lays out the infographic — on one colour system.", color: "#f472b6" },
          { name: "Theme Builder", bold: "The stylist.", body: " Palette, type, toppings and heroes as one bundle — from a preset, your brand guide, or a deck you already gave.", color: "#22d3ee" },
          { name: "Slide Composer", bold: "The conductor.", body: " Pacing, balance, focus. Composes one slide into any deck — new or existing — with its neighbours in mind.", color: "#facc15" },
          { name: "Element Generator", bold: "The builder.", body: " Text boxes, metrics, tables, icons, shapes — the atoms of every slide, regenerated one at a time on request.", color: "#c084fc" },
          { name: "Presenter", bold: "The one that stays late.", body: " Narrates the published deck, answers the audience from your sources, in a voice you choose.", status: "In build", color: "#a78bfa" },
        ],
      },
      guardrails: {
        label: "Guardrails", eyebrow: "Guardrails", title: "Four things the team will never do.",
        cards: [
          { number: "01", title: "Ship without your yes", body: "Plan, strawman, every slide — each waits for you. Autopilot is a setting you choose, not a default." },
          { number: "02", title: "Invent a number", body: "Every figure carries its source. Web estimates are labelled estimates. Your own numbers are labelled yours." },
          { number: "03", title: "Name your private files", body: "A published deck may use your uploads to answer — it never tells the audience they exist." },
          { number: "04", title: "Hide its thinking", body: "The chain of thought is on screen while they work. If you don't like where it's going, you'll know before it gets there." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: ["Take the ", "chair."],
        lede: "One sentence to the Director is enough to start. Bring a deck and it starts further along.",
        build: "Build a deck", bring: "Bring a deck",
      },
    },
    pricing: {
      metadata: { title: "Pricing — Deckster" },
      start: {
        label: "Pricing",
        eyebrow: "Pricing",
        title: "Priced for how you ",
        titleAccent: "present.",
        lede: "Three tiers, top-ups anytime, no seats math. What you bring — files, research, your knowledge graph — is what unlocks the next tier.",
        cue: "Compare the tiers",
        tiers: [
          {
            id: "starter",
            name: "Starter",
            price: "$20",
            suffix: "per user / mo",
            blurb: "Everything to ship a polished deck on your own.",
            features: [
              "Director, Content, Visualizer, Slide Composer, Theme Builder",
              "All chart, diagram and infographic types",
              "Custom themes & templates from your own decks",
              "PowerPoint & PDF export — no watermark",
              "Top-up credits anytime",
            ],
            note: "Generous monthly credits for typical workloads.",
            action: "Get started",
          },
          {
            id: "pro",
            tag: "Most popular",
            name: "Pro",
            price: "$50",
            suffix: "per user / mo",
            blurb: "For people who present every week — with research.",
            features: [
              "Everything in Starter, plus:",
              "Researcher: live data from the open web",
              "Upload your own files as source material",
              "Analyst: finds the story in your numbers",
              "Higher monthly credit allowance",
            ],
            note: "Suited to research-heavy and frequent presenters.",
            action: "Get started",
          },
          {
            id: "premium",
            name: "Max",
            price: "$100",
            suffix: "per user / mo",
            blurb: "For people who present as their core work.",
            features: [
              "Everything in Pro, plus:",
              "Knowledge Graph: agents learn your domain across decks",
              "Priority generation queue",
              "Highest monthly credit allowance",
            ],
            note: "Built for the heaviest, most demanding workflows.",
            action: "Get started",
          },
        ],
      },
      matrix: {
        label: "Compare",
        eyebrow: "Tier by tier",
        title: "What each tier unlocks.",
        headings: ["Capability", "Starter", "Pro", "Max"],
        rows: [
          { name: "Build", detail: " — Director + the specialist team, all element types", values: [true, true, true] },
          { name: "Bring", detail: " — templates from your own decks, custom themes, Theme Studio", values: [true, true, true] },
          { name: "Export", detail: " — PowerPoint & PDF, no watermark", values: [true, true, true] },
          { name: "Research", detail: " — Researcher on the open web, cited", values: [false, true, true] },
          { name: "Your files", detail: " — uploads as source material, with provenance", values: [false, true, true] },
          { name: "Analyst", detail: " — the story in your numbers", values: [false, true, true] },
          { name: "Knowledge graph", detail: " — your documents cited across decks", values: [false, false, true] },
          { name: "Priority queue", detail: "", values: [false, false, true] },
          { name: "Present", detail: " — publish & share, audience Q&A, narration", values: [null, null, null], tag: "rollout by tier: decision pending" },
        ],
      },
      faq: {
        label: "Questions",
        eyebrow: "Top-ups & questions",
        title: "Need more in a busy month?",
        lede: "Top-up credits on every tier, no commitment. Usage depends on the length and visual richness of each deck — a 30-slide research-heavy deck costs more than a 10-slide update.",
        questions: [
          { question: "What counts as usage?", answer: "Every agent call — research, writing, charts, theming. Reusing a template or a theme costs less than building from scratch, because the structure already exists." },
          { question: "Do my uploads leave my account?", answer: "No. Uploads, extracted facts and your knowledge graph are yours. Purge or export them at any time." },
          { question: "Can I switch tiers?", answer: "Any time. Upgrades apply immediately; downgrades at the end of the billing month." },
          { question: "Is there a watermark?", answer: "Never. PowerPoint and PDF exports are clean on every tier." },
          { question: "Can my team share templates?", answer: "Yes — templates and themes made from your decks can be shared with people in your workspace." },
          { question: "What about publishing and narration?", answer: "Publishing and audience Q&A are live; narration is in build. Which tiers include them is a decision we're finalising." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Start with what you ", titleAccent: "have.",
        lede: "A deck you've already given is the fastest way in. So is a single sentence.",
        build: "Get started", bring: "Bring a deck",
      },
    },
    about: {
      metadata: { title: "About — Deckster" },
      start: {
        label: "About", eyebrow: "Our story", title: "We're keeping the human in the ", titleAccent: "loop.",
        lede: "Deckster started from a simple conviction: a deck should come from a conversation, not a blank slide and a lost evening. It grew into a second one — that the best decks come from a team that shows its work and asks before it commits.",
        trust: ["Built by people who present for a living", "Every feature starts with a real deck"],
        cue: "What we believe",
      },
      principles: {
        label: "Principles", eyebrow: "What we believe", title: "Three principles, every release.",
        cards: [
          { number: "01", title: "Your yes, every time", body: "Automation that asks is not slower — it is trustworthy. The plan, the strawman and every slide wait for you." },
          { number: "02", title: "Your knowledge, your provenance", body: "What you upload stays yours, is cited as yours, and can be purged or exported at any time. Web estimates are labelled as such." },
          { number: "03", title: "Nothing is a black box", body: "The chain of thought is on screen while the team works. You can pause it, steer it, or take the wheel on the canvas." },
        ],
      },
      story: {
        label: "Story", eyebrow: "How Deckster grew", title: "From a blank slide to a deck that presents itself.",
        steps: [
          { number: "2025 · THE BLANK SLIDE", title: "A conversation, not a canvas", body: "The first Deckster built a whole deck from a chat — and made the agent team the protagonist." },
          { number: "2026 · PRECISION", title: "Deck, slide, element", body: "Control moved to every altitude: compose one slide into any deck, regenerate one element, keep the rest." },
          { number: "2026 · BRING", title: "Your decks become templates", body: "Past presentations deconstructed into reusable structure; documents into a knowledge graph; brands into theme bundles." },
          { number: "NEXT · PRESENT", title: "The deck that stays late", body: "Published decks that narrate, answer the audience and show up in many rooms at once." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Come build ", titleAccent: "with", titleTail: " us.",
        lede: "Try it on a deck you've already given. Tell us what the team got wrong — that is how it gets better.",
        build: "Build a deck", email: "hello@deckster.xyz",
      },
    },
    learn: {
      metadata: { title: "Learn — Deckster" },
      start: {
        label: "Learn", eyebrow: "Learn", title: "Learn at your ", titleAccent: "altitude.",
        lede: "Everything in Deckster happens at one of three levels. Pick the one you're working at.",
        cards: [
          { name: "Deck", title: "Talk to the Director", body: "Briefs, plans, strawmans, research toggles, themes, export. The whole-deck conversation.", example: "“Build a 16-slide review from my board pack.”", tags: ["Quick start", "Your first deck", "Research options"] },
          { name: "Slide", title: "Compose one slide", body: "Add or refine a single slide in any deck, with its neighbours as context. Layout, density, focus.", example: "“Add a slide after 4 comparing latency by team.”", tags: ["Slide Composer", "Refine in place", "Layouts"] },
          { name: "Element", title: "Regenerate one piece", body: "Charts, tables, metrics, diagrams, infographics, text — change one without touching the rest.", example: "“Make this chart a waterfall and cite the source.”", tags: ["Element panel", "Chart types", "Editing on canvas"] },
        ],
        cue: "Your first deck",
      },
      first: {
        label: "First deck", eyebrow: "Your first deck", title: "Five steps, one evening back.",
        steps: [
          { number: "01 · BRING", title: "Drop what you have", body: "A past deck, a report, your brand guide. Optional — but it makes everything after look like you." },
          { number: "02 · BRIEF", title: "Tell the Director", body: "One sentence or a full brief. Toggle web research, deep research or your knowledge graph." },
          { number: "03 · APPROVE", title: "Say yes to the plan", body: "Sections, slide count, who does what. Change anything in plain English." },
          { number: "04 · REFINE", title: "Edit at any altitude", body: "Reshape a slide, regenerate an element, switch the theme — the rest stays intact." },
          { number: "05 · SHIP", title: "Export or publish", body: "PowerPoint, PDF — or a link that narrates and answers questions while you're away." },
        ],
      },
      guides: {
        label: "Guides", eyebrow: "Guides & help", title: "Stuck? Get unblocked.",
        cards: [
          { tag: "Getting started", title: "Quick start · Your first presentation · Understanding the team", body: "The three reads for a first session." },
          { tag: "Builder guide", title: "Chat · Editing slides · Elements · Exports", body: "Every panel in the builder, at every altitude." },
          { tag: "Bring", title: "Templates from your decks · Knowledge graph · Theme Studio", body: "How your material becomes reusable." },
          { tag: "Present", title: "Publishing · Access modes · Audience Q&A · Narration", body: "What a published deck can and cannot say." },
          { tag: "Reference", title: "Agent reference · API · Shortcuts", body: "For people who want the full map." },
          { tag: "Help", title: "Help centre · a human on the other end", body: "Answers, quick-start steps and a direct line to support." },
        ],
      },
      close: {
        label: "Begin", eyebrow: "Begin", title: "Ship your first deck ", titleAccent: "today.",
        build: "Build a deck", bring: "Bring a deck",
      },
    },
  },
} as const

/** Public image names are design slots; some contain a different source-deck slide. */
export const SHOWCASE_SLOTS = {
  1: { slide: 1, title: "A new operating model moves" },
  2: { slide: 2, title: "Driving Business Agility through a Five-Step Model" },
  3: { slide: 3, title: "Managing the Ownership Chain for Product Changes" },
  4: { slide: 11, title: "Strengthening the Six Capabilities of Modern Delivery" },
  5: { slide: 5, title: "A Weekly Loop to Replace the Board" },
  6: { slide: 6, title: "Optimizing Decision Forums and Governance Cadence" },
  7: { slide: 7, title: "Teams Climb Five Levels of Delivery Maturity" },
  8: { slide: 9, title: "Where each decision should live" },
  9: { slide: 16, title: "Next Wave Lowers Later Costs" },
  10: { slide: 10, title: "Four Core Pillars of the Operating Model" },
  11: { slide: 12, title: "The rollout runs from June 2026 to June 2027" },
  12: { slide: 14, title: "Hiring Worked: Eleven Engineers Joined Last Quarter" },
} as const

export function showcaseAlt(slot: number, fallbackTitle?: string) {
  const source = SHOWCASE_SLOTS[slot as keyof typeof SHOWCASE_SLOTS]
  return `Slide ${source?.slide ?? slot} of the showcase deck: ${source?.title ?? fallbackTitle ?? "Untitled slide"}`
}
